### ISSUE TITLE
[C-1673] Eagle Eye onboarding wizard redirects back to first step

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#1009]
**Problem**

I had a user call with PandasAI. When he tried to set up Eagle Eye, he went through the whole set up wizard but got redirected to the starting screen again after the last step. After a couple of seconds the Eagle Eye feed view finally appeared. The user previously thought Eagle Eye just doesn't work.

I assume that this might be related to a caching issue.

**Solution**

We should make sure that the user gets redirected to the actual feed after setting up Eagle Eye. Otherwise, the onboarding UX is quite poor.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1673](https://linear.app/crowddotdev/issue/C-1673/eagle-eye-onboarding-wizard-redirects-back-to-first-step)</sub>

**Comment by Dhruwang** [comment]
On it !
