### ISSUE TITLE
[C-1740] Scope meetup.com integration

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#1051]
Get activities & members from [https://www.meetup.com/](https://www.meetup.com/)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1740](https://linear.app/crowddotdev/issue/C-1740/meetup-integration)</sub>

**Comment by jonathimer** [comment]
requested by a user

**Comment by jonathimer** [comment]
got requested by another customer

**Comment by bnchi** [comment]
Do you guys want help with this ? If yes which kind of activities would you think makes sense to track ? 

Meetup app have groups, events and activities(comments on a group) among other things

**Comment by jonathimer** [comment]
Hey @bnchi! Yes, that would be awesome. Let us get a bit more specific on requirements first. Also happy to set up a bounty for it!

**Comment by bnchi** [comment]
Alright looking forward for the requirements
