### ISSUE TITLE
[C-1814] Add a new role "Collaborator"

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#1101]
user feedback

*right now, there is only view-only and admin as roles but something in the middle like "view & enrich & create/edit tasks" would be cool to have, for example. Admin seems to have access to integrations etc. which is not ideal but we'll do it for now.*

**Suggestion**

Add a new role called "User" (besides "Read-only" and "Admin").

Users will be able to:

* View all parts of the app (all permission of "Read-only")
* Enrich members
* Create/edit tasks
* Create/edit notes
* Create/edit automations
* Invite other users
* Use Eagle Eye

User won't be able to:

* Edit integrations
* Change plan

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1814](https://linear.app/crowddotdev/issue/C-1814/add-a-new-role-user)</sub>

**Comment by Ashutosh-Bhadauriya** [comment]
@jonathimer can you please assign this to me? Thanks!

**Comment by Bhardwaj-Himanshu** [comment]
Hi @jonathimer @Ashutosh-Bhadauriya, let me know about the progress and if I could be of any help in creating it! Cause won't want to create a pull request causing conflicts!

Also, could you elaborate a little on what you mean about users not able to "change plan", like what plan are we talking about here, most probably not a subscription fee?

Also, I am new to the repository, I am covering the contributing.md, but to get a quick/indepth view of how things are working in crowd.dev, are there any new launches or new update videos covering the UI/UX structures and if you could point me to the same?
Thanks(pardon for the tags)

**Comment by Ashutosh-Bhadauriya** [comment]
@Bhardwaj-Himanshu you can take this, I am facing issues setting up the project locally

**Comment by Bhardwaj-Himanshu** [comment]
Let me help you with the problems in setting up the project @Ashutosh-Bhadauriya, let me know if there is something I could do to help!

Meanwhile, pardon for the retag but as me also being new, could you also mention the lines in code or example that are `in creation of a new role of any kind in the codebase` so that I have a reference of what is being asked and how to implement it here? @jonathimer
