### ISSUE TITLE
[C-1821] Member profile: Name and Job title are not centered towards picture + too much spacing

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#1110]
<img width="349" alt="Bildschirmfoto 2023-07-12 um 19 53 51" src="https://github.com/CrowdDotDev/crowd.dev/assets/41432658/888a5130-7505-40c1-829d-9b27947c0c39">

**Comment by neilchauhan2** [comment]
Hi @jonathimer, I'm looking forward to contributing to crowd.dev, and would love to take this issue up. Can you please assign this to me?

**Comment by Satyam-G5** [comment]
@jonathimer Could you please assign this issue to me? I would like to work on it. Thank you!
