### ISSUE TITLE
[C-1827] Found null value in the emails list with actual emails

### ISSUE THREAD

**Issue by yeganathan18** [CrowdDotDev/crowd.dev#1117]
Check the below screenshot , we can find a `null` value in the emails list of the api response which also appears as blank item when rendered in the UI.

![Linear-hosted image](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/c8978e08-4630-401f-a8cb-a9c30a1decab/00870c71-d05b-49a3-8090-79e5498a1eb6)
[Image source](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/c8978e08-4630-401f-a8cb-a9c30a1decab/00870c71-d05b-49a3-8090-79e5498a1eb6)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1827](https://linear.app/crowddotdev/issue/C-1827/found-null-value-in-the-emails-list-with-actual-emails)</sub>

**Comment by jonathimer** [comment]
can we maybe do a quick fix here so that emails with NULL value dont get displayed anymore? I see it in almost all member profiles

**Comment by yeganathan18** [comment]
Done! I've opened a PR https://github.com/CrowdDotDev/crowd.dev/pull/1186
