### ISSUE TITLE
[C-1841] Selecting members directly opens tag dialogue

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#1127]
[https://www.loom.com/share/755155918785486d8f2a2ae9b7a0fad6?sid=cfb9f7a9-de56-478a-89c5-7e200514409e](https://www.loom.com/share/755155918785486d8f2a2ae9b7a0fad6?sid=cfb9f7a9-de56-478a-89c5-7e200514409e)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1841](https://linear.app/crowddotdev/issue/C-1841/selecting-members-directly-opens-tag-dialogue)</sub>

**Comment by yeganathan18** [comment]
Hey, just a heads up. It's not just the popover; the `BulkUpdateTags` component on the FE is also broken. I'm increasing the estimate by a point and will get it fixed asap.
