### ISSUE TITLE
[C-1883] Re-direct app.crowd.dev to app.crowd.dev/auth/signup (if user is not logged in)

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#1149]
**Problem**

When visiting [https://app.crowd.dev/](https://app.crowd.dev/), users can re-directed to [https://app.crowd.dev/auth/signin](https://app.crowd.dev/auth/signin) if they are not logged in

**Solution**

Users should be re-directed to [https://app.crowd.dev/auth/sign](https://app.crowd.dev/auth/signin)up if they are not logged in to increase conversion

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1883](https://linear.app/crowddotdev/issue/C-1883/re-direct-appcrowddev-to-appcrowddevauthsignup-if-user-is-not-logged)</sub>

**Comment by peoray** [comment]
@joanagmaia is this still a valid issue? If so, please provide more context as I cannot reproduce this

**Comment by a0m0rajab** [comment]
I think it's resolved.

**Comment by yeganathan18** [comment]
@peoray @a0m0rajab, I think the issue still holds up. To perform a quick test, I would do the following steps:

1. Launch an incognito browser window
2. Navigate to https://app.crowd.dev/
3. We're still being redirected to https://app.crowd.dev/auth/signin

However, the improvement suggested here aims to redirect users who aren't signed in to https://app.crowd.dev/auth/signup instead.

**Comment by a0m0rajab** [comment]
@yeganathan18 with your steps if works as expected, since we are not logged in the incognito mode

**Comment by yeganathan18** [comment]
Exactly, so we should be changing the redirection from `/signin` to `/signup`.

**Comment by peoray** [comment]
@a0m0rajab wanna pick it up?

**Comment by a0m0rajab** [comment]
Yeah, I was thinking to pick it up, mostly the code needed to change is in this lines: 

https://github.com/CrowdDotDev/crowd.dev/blob/e91b729162b96eb4707bf0ab91cfbc5fe02830ef/frontend/src/middleware/auth/auth-guard.js#L15-L40

@peoray if you like you we can collaborate on it? (yes, it's simple but yeah)

**Comment by a0m0rajab** [comment]
@peoray Thanks for that! If you feel to pick it up, it's okay for me too!
