### ISSUE TITLE
[C-1939] More than two emails after member enrichment make the emails column Inconsistent

### ISSUE THREAD

**Issue by yeganathan18** [CrowdDotDev/crowd.dev#1164]
Following member enrichment (see screenshot), the 'emails' column overflowed with multiple entries, causing UI inconsistencies. Instead, we could display '+2' or similar to represent additional emails, akin to our handling of excess tags.

![Screenshot 2023-07-22 at 12.15.56 AM.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/55f22c88-1059-4f4c-91ad-5840988389a6/8a8237b2-4a95-4bbc-858a-6650317d9cd6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FlYmVjN2FkLTU2NDktNDc1OC05YmVkLTA2MWY3MjI4YTg3OS81NWYyMmM4OC0xMDU5LTRmNGMtOTFhZC01ODQwOTg4Mzg5YTYvOGE4MjM3YjItNGE5NS00YmJjLTg1OGEtNjY1MDMxN2Q5Y2Q2IiwiaWF0IjoxNjg5OTY1ODEyLCJleHAiOjE2OTAwNTIyMTJ9.SwCgJt3pqDB3m6ugTVFlC1Q4GnlwsVjgExvKj0RLHAs)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1939](https://linear.app/crowddotdev/issue/C-1939/more-than-two-emails-after-member-enrichment-make-the-emails-column)</sub>

**Comment by Bhardwaj-Himanshu** [comment]
Hi @yeganathan18 , let me know on how you are working to tackling this issue!
The proposed solution is quite right to display +X which would maintain consistencies within the UI.
-which in my little knowledge could be targeted via printing on the first 3 or 2 emails, but I don't know how to tackle on the same!
And let me know if I could be of any help to you!
Thanks

**Comment by yeganathan18** [comment]
Hey, appreciate your interest in the fix!

In the case of tags, when we add more than 3-4 for a member it shows up like `tag1` `tag2` `tag3`followed by a `+2` and I'd love to see similar stuff for the emails column as well if it's more than two/three, where hovering over the number would reveal the leftover emails.

I'm also looping in our product designer @nunoeufrasio for a quick suggestion 😄

**Comment by Bhardwaj-Himanshu** [comment]
Yep, thanks for the warm regards;)
Let me know when we could start working on this enhancement feature and if I could be of any help to you!

**Comment by nunoeufrasio** [comment]
@Bhardwaj-Himanshu @yeganathan18 hope this visual reference can help 🙂 when more than 3, apply the +N pattern. Let me know if you need anything else.
<img width="892" alt="emails column" src="https://github.com/CrowdDotDev/crowd.dev/assets/22342669/93209a4c-fae6-412c-a908-6ad0c1127a11">

**Comment by yeganathan18** [comment]
Hey @Bhardwaj-Himanshu!, I'm really stoked you're eager to learn! Unfortunately, I've got my plate full with other high-priority tasks at the moment and can't dive into this issue myself right now.

But, our team would be super happy to help you if you're interested in working on the issue 😄 

By the way, don't forget to jump on our [Discord server](https://crowd.dev/discord) if you haven't already. (Insider tip: It's a great place to meet and chat with other contributors!)

**Comment by Bhardwaj-Himanshu** [comment]
I would love to hop onto this issue then @yeganathan18 . Overflowing your plate with my DM's too then;)

**Comment by yeganathan18** [comment]
You can find the code for members table in: `/frontend/src/modules/member/components/list/member-list-table.vue`

**Comment by peoray** [comment]
Picking this up :)

**Comment by yeganathan18** [comment]
@peoray Thanks for picking up the issue! I've assigned the issue to you 😄
