### ISSUE TITLE
"Member name" filter in Members list

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1239]
### Describe the problem

Currently, the only way to look for a member (Members list) is via search input. That does not provide enough flexibility if we think of use cases like finding duplicates/similar member names, or making use of filter operators (contains, does not contain, etc.)

### Describe the improvement

Add a new text-based filter - Member name - to Members list. Position in filters list: 1st
![Screenshot 2023-08-08 at 14 04 48](https://github.com/CrowdDotDev/crowd.dev/assets/22342669/e356f7b3-47d0-4ed7-9625-7d99428a6e68)

**Comment by joanagmaia** [comment]
> Can I be assigned to this?

Yes of course 😄 Let me know if you need any help on this!

**Comment by peoray** [comment]
@joanagmaia @nunoeufrasio using the STRING option for filters, I can't find any way to have the include checkbox. can you help?
