### ISSUE TITLE
[C-2037] "Organization" filter in Members, Organizations, and Activities lists

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1240]
### Describe the problem

Currently, the only way to look for an organization is via search input. That does not provide enough flexibility if we think of use cases like filtering multiple organizations, or making use of filter operators (contains, does not contain, etc.)

### Describe the improvement

Add a new multi-select filter - Organization - in Members, Organizations and Activities lists. Position in filters list: 2nd (Members) / 1st (Organizations) / 5th (Activities)

<img width="428" alt="Screenshot 2023-08-09 at 06 26 27" src="https://github.com/CrowdDotDev/crowd.dev/assets/22342669/56bcec6d-b466-41ea-856d-e6d39afe4197">

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2037](https://linear.app/crowddotdev/issue/C-2037/organization-filter-in-members-organizations-and-activities-lists)</sub>

**Comment by nunoeufrasio** [comment]
✅ updated

**Comment by peoray** [comment]
@nunoeufrasio the image is not visible :)

**Comment by nunoeufrasio** [comment]
@peoray 😉
<img width="428" alt="Screenshot 2023-08-09 at 06 26 27" src="https://github.com/CrowdDotDev/crowd.dev/assets/22342669/56bcec6d-b466-41ea-856d-e6d39afe4197">

**Comment by peoray** [comment]
@joanagmaia please can you provide more context
My assumption is that this would use MultiSelectAsync as seen on members and tags. Also, it seems both are limited to 10 items.

**Comment by joanagmaia** [comment]
Hey @peoray, of course.
That's right. This would follow a very similar approach to the one in `frontend/src/modules/activity/config/filters/member/config.ts`. Basically, in this filter config you define the type as `MultiSelectAsync`. Then you define options to fetch the remote values with `remoteMethod` and `remotePopulateItems`. You can use `listAutocomplete` from the service to get the response for organizations.

And yes, the results are limited to 10 options, you'll only get different results if you search for something else.
Hopefully this helps 😄

**Comment by peoray** [comment]
Thank you @joanagmaia , it was very helpful
