### ISSUE TITLE
[C-2038] "Job title" filter in Members list

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1241]
### Describe the problem

Currently, there's no proper way to look for members with certain job titles.

### Describe the improvement

Add a new text-based filter - Job title - to Members list. Position in filters list: 3rd

![Screenshot 2023-08-08 at 14 41 48](https://github.com/CrowdDotDev/crowd.dev/assets/20134207/6c6d36d0-6348-4f08-8c8c-8990a2a6552f)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2038](https://linear.app/crowddotdev/issue/C-2038/job-title-filter-in-members-list)</sub>

**Comment by peoray** [comment]
Picking this up.

@joanagmaia the jobTitle looks to be nested in `attributes.jobTitle.default`. Does this affect how I use similar or I can just use `jobTitle`?

**Comment by peoray** [comment]
@nunoeufrasio the image is not visible :)

**Comment by joanagmaia** [comment]
@peoray yeah you can also take this one 😄 
Just updated the description with the image, and same as the previous issue. No need to include the "Include" checkbox.

Related to your question, you should use `attributes.jobTitle.default`
