### ISSUE TITLE
[C-2039] "Headcount" multi-select filter

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1242]
### Describe the problem

Currently, the "Headcount" filter in Organizations list does not offer enough flexibility as a single select field with size ranges.

### Describe the improvement

Change the "Headcount" filter type from single select (size ranges) into a multi-select filter including a new option ">1000". Position in filters list: same.

<img width="413" alt="Screenshot 2023-08-14 at 10 03 03" src="https://github.com/CrowdDotDev/crowd.dev/assets/20134207/3ee87e61-3c57-4701-8568-b8c0154b9b60">

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2039](https://linear.app/crowddotdev/issue/C-2039/headcount-multi-select-filter)</sub>

**Comment by jonathimer** [comment]
👍

**Comment by joanagmaia** [comment]
At the moment `headcount/size`is a string in BE. So the values are actually stored as `0-10`, preventing the frontend from treating it as a number.

This ticket will need both BE and FE

**Comment by jonathimer** [comment]
Right now, headcount consists of those different steps:

![Bildschirmfoto 2023-08-09 um 09.33.07.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/85c115b0-b329-4d9b-ac61-aefc543919db/ff78f576-5b52-4810-a369-73b77469f7db)

Why don't we just turn this into a multi-select so you can just select ALL the options that are relevant. I dont think we necessarily need to parse this range into a number.

**Comment by nunoeufrasio** [comment]
was based on this customer feedback 

"*Some filters are lacking multi-select or custom values. E.g. I would like to query all organisations > 1000 employees. It seems like this is not possible, and I have to look at various buckets individually (500-1000, 1001-5000, etc)"* 

Either we tweak the ranges (e.g. 1000+) and apply multi-select or make it totally flexible

**Comment by jonathimer** [comment]
Lets make it a multi-select.

It doesn't really make sense to parse that data to a number. This will give a sense of accuracy that doesn't really exist.

"I have to look at various buckets individually" -> This will be fixed by having a multi-select.

**Comment by peoray** [comment]
can I pick this up?

**Comment by peoray** [comment]
@nunoeufrasio the image is not visible. I get a `Invalid upstream response (401)` error

**Comment by joanagmaia** [comment]
Hey @peoray yeah feel free to pick this one up as well 😄 
Also, updated the image in the description

**Comment by nunoeufrasio** [comment]
@peoray 
<img width="413" alt="Screenshot 2023-08-14 at 10 03 03" src="https://github.com/CrowdDotDev/crowd.dev/assets/22342669/19d82faf-0aca-4a57-803d-ccd083edb28d">

**Comment by joanagmaia** [comment]
@nunoeufrasio @jonathimer The canonical values we support are the ones listed here [https://docs.peopledatalabs.com/docs/company-sizes](https://docs.peopledatalabs.com/docs/company-sizes)

Instead of just displaying one extra option (>1000), I would add the remaining ones listed on that table, offers more flexibility in terms of search, and matches the values we actually allow/display.

A contributor is working on this at the moment

**Comment by joanagmaia** [comment]
Also aligned with Nuno. Will add the remaining options
