### ISSUE TITLE
[C-2042] Improve Slack bot installation warning

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1244]
### Describe the problem

Currently, after users connect Slack integration, we ask to also connect the Slack bot as a required step to fetch data from Slack channels. We have reports of users missing/not acknowledging this step, and we can assume that the current warning message (banner in Integrations page) is not prominent enough.

### Describe the improvement

Change the current warning banner on top of Integrations page with a dialog, including a CTA redirecting users to [Docs](https://docs.crowd.dev/docs/slack-integration) page. The dialog is prompted when users return from Slack auth page and is only dismissed when users hit the CTA button (link opens in the tab).

![image.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/9cc16558-134c-49f2-aa30-58b73a09c071/fe2d148f-097c-41bf-8746-6a6bb7306db3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FlYmVjN2FkLTU2NDktNDc1OC05YmVkLTA2MWY3MjI4YTg3OS85Y2MxNjU1OC0xMzRjLTQ5ZjItYWEzMC01OGI3M2EwOWMwNzEvZmUyZDE0OGYtMDk3Yy00MWJmLTg3NDYtNmE2YmI3MzA2ZGIzIiwiaWF0IjoxNjkxNTcxNDM4LCJleHAiOjE2OTE2NTc4Mzh9.SjepiHfoUeIjZpSK2NtwYyajmV3xJp3q4wtGS47ZIp4)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2042](https://linear.app/crowddotdev/issue/C-2042/improve-slack-bot-installation-warning)</sub>

**Comment by jonathimer** [comment]
Couldn't we add a screen where somebody adds "@crowd.dev" to their Slack? Would be cool to make it more visual

**Comment by jonathimer** [comment]
@nunoeufrasio

**Comment by joanagmaia** [comment]
@jonathimer when you mention a screen would it be some visuals inside the modal?

To be honest I think having a CTA that leads to a page with the instructions should do the trick since it's a connection occurring outside our app and slack's instructions should be pretty clear

**Comment by jonathimer** [comment]
Yes! Thats fantastic. 🙌
