### ISSUE TITLE
[C-2043] "Last synced" timestamp on connected integrations

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1245]
Include a timestamp on each connected integration referring to the last time the data was synced, and therefore providing additional info in case of an unstable connection, or help users set expectations.

![Screenshot 2023-08-08 at 15.10.12.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/e85a10d5-b632-4f6c-aced-346183f00396/5717dc9a-ead9-40da-90ff-933c825b596d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FlYmVjN2FkLTU2NDktNDc1OC05YmVkLTA2MWY3MjI4YTg3OS9lODVhMTBkNS1iNjMyLTRmNmMtYWNlZC0zNDYxODNmMDAzOTYvNTcxN2RjOWEtZWFkOS00MGRhLTkwZmYtOTMzYzgyNWI1OTZkIiwiaWF0IjoxNjkxNTA0MTc0LCJleHAiOjE2OTE1OTA1NzR9.ldZRjZ-yklPWdfQaLGOpvVinSKwEDzgHq-JhdHYF-68)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2043](https://linear.app/crowddotdev/issue/C-2043/last-synced-timestamp-on-connected-integrations)</sub>

**Comment by jonathimer** [comment]
👍
