### ISSUE TITLE
[C-2044] Prevent non-admin GH users from setting up GH

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1246]
Every time users hit GH "Connect button", we trigger an informative dialog explaining that the process can only be concluded by GH admin users. Users can either continue to GH or jump into to Docs page for further reading (opening in the tab).

![Screenshot 2023-08-08 at 15.33.32.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/44309324-5951-40db-b562-ee15a9ab2785/2ee12666-c284-49b5-9748-2d0396b1c829?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FlYmVjN2FkLTU2NDktNDc1OC05YmVkLTA2MWY3MjI4YTg3OS80NDMwOTMyNC01OTUxLTQwZGItYjU2Mi1lZTE1YTlhYjI3ODUvMmVlMTI2NjYtYzI4NC00OWI1LTk3NDgtMmQwMzk2YjFjODI5IiwiaWF0IjoxNjkxNTA1MjQ1LCJleHAiOjE2OTE1OTE2NDV9.hDHYnHxkeFZDEQRM0IOKvk96weaaYjW9Dq90eIx3eNk)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2044](https://linear.app/crowddotdev/issue/C-2044/prevent-non-admin-gh-users-from-setting-up-gh)</sub>

**Comment by jonathimer** [comment]
i think the CTAs should be like:

**Are you the admin of your GitHub organization?**

* Yes, I'm the admin of our GitHub organization
* Invite admin. → leading to the user settigs

  I would also not use primary color for option 1, so the user really stops and thinks about it for a second.

  cc @nunoeufrasio

**Comment by joanagmaia** [comment]
I agree with @jonathimer here and it's a good point on the button. Since it has so much feature in the dialog, I think it will be easier for users to just click on the continue button and not read the message.

I like the suggestions above 😄

**Comment by nunoeufrasio** [comment]
Partially agree with the 2nd CTA, as the GH admin may already be a workspace user, but here's the an update with some copy tweaks, to prevent misunderstandings around crowd.dev admin / GH admin

![Screenshot 2023-08-09 at 07.59.49.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/3fadde5e-bac2-44dc-98c5-8ad6dac072e1/d1c0c2b5-02fb-47c9-97a3-0af340e6e047)

**Comment by peoray** [comment]
@nunoeufrasio the image is not visible :)

**Comment by nunoeufrasio** [comment]
@peoray 😉
<img width="454" alt="Screenshot 2023-08-09 at 07 59 49" src="https://github.com/CrowdDotDev/crowd.dev/assets/22342669/e61734c3-eb34-474a-900e-0d50d323de8a">
