### ISSUE TITLE
[C-599] Option to turn off sentiment analysis

### ISSUE THREAD

**Issue by Charlotte0709** [CrowdDotDev/crowd.dev#1272]
Give users the ability to turn off sentiment analysis as it can misrepresent community efforts / discourage people to share with other team members.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-599](https://linear.app/crowddotdev/issue/C-599/option-to-turn-off-sentiment-analysis)</sub>

**Comment by joanagmaia** [comment]
Duplicated of this one [C-2078](https://linear.app/crowddotdev/issue/C-2078/allow-to-disable-sentiment-analysis), will cancel this one
