### ISSUE TITLE
[C-1137] Email overflow on Member profile

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1289]
If email is too large, it will overflow the side card of the Member's profile.

**Suggestion:** Truncate email at a maximum width

![Screenshot 2023-04-06 at 15 29 44](https://github.com/CrowdDotDev/crowd.dev/assets/63534555/ebe3c53a-dea3-4984-9431-393875229c0f)

How to solve this?
1. If email overflows the parent container, truncate text with ellipsis
2. If email is truncated, to avoid losing information, on hover display a tooltip with the entire email. You can use `el-tooltip` for the tooltip element.
3. If email is truncated, the link icon on the right should still show up, so truncate the email so that the icon is still displaying. You can give a gap of 8px between text and icon.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1137](https://linear.app/crowddotdev/issue/C-1137/email-overflow-on-member-profile)</sub>

**Comment by peoray** [comment]
@joanagmaia can I pick this up? Also please update the image.

What's the maximum width are looking at here?

**Comment by peoray** [comment]
Is this the same ticket?
https://github.com/CrowdDotDev/crowd.dev/issues/1164

**Comment by yeganathan18** [comment]
@peoray No this ticket is different from what you mentioned. Both happen at two different places and contexts, hope this helps! 🙂

**Comment by peoray** [comment]
@yeganathan18 thanks. can you provide additional context to this issue especially the image @joanagmaia shared? I can't view it

**Comment by yeganathan18** [comment]
@peoray I apologize for that oversight and I've updated the issue description now. Here's the additional context: If the email text is too large, it overflows instead of being truncated. If it exceeds the maximum width it can grow then truncate it like `47258917+CallmeMehdiusers@users.noreply...`

**Comment by peoray** [comment]
thank you. picking this up as well :)

**Comment by yeganathan18** [comment]
Awesome! Thanks for the help 🙂 

I've assigned the issue to you and please let us know if you need any help 🙏🏻

**Comment by joanagmaia** [comment]
@peoray thanks for the interest in contributing again!
Exactly what @yeganathan18 mentioned, if it overflows, the section width, truncate it.
To avoid losing information, if it truncates can you display a tooltip on hover with the entire text? I'll also update the description with that

Ps. Today I'll go over the github issues to add missing images and description
