### ISSUE TITLE
[C-2249] Add channel filter to the homepage

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1429]
<sub>From [SyncLinear.com](https://synclinear.com) | [C-2249](https://linear.app/crowddotdev/issue/C-2249/add-channel-filter-to-the-homepage)</sub>

**Comment by nunoeufrasio** [comment]
@joanagmaiagmaia @jonathimer 2 options, I prefer A but let me know what you think 

[https://www.figma.com/file/OCnEUoOe5lrwQyQUGNJ38i/1.-Home?type=design&node-id=1728-21058&mode=design](https://www.figma.com/file/OCnEUoOe5lrwQyQUGNJ38i/1.-Home?type=design&node-id=1728-21058&mode=design)

**Comment by joanagmaia** [comment]
I also prefer option A. It matches our approach for Channel filters in other app pages.

In terms of flow, did you design it so Channels depend on the selected platform? If no platform is selected, we don't show the Channel filter?

**Comment by nunoeufrasio** [comment]
exactly, if default **Platform: All** …channel filter is not visible. Same if the selected platform does not include channels

**Comment by joanagmaia** [comment]
Sounds good to me
