### ISSUE TITLE
[C-2314] Add tooltip to Organizations' identities in Organizations list

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1495]
When hovering an Organization identity with a url, we should display a tooltip with the following content: <platform> profile <link icon>.

It should follow the same approach we have in members list

This will help the user to understand which profiles are clickable or not
![Screenshot 2023-09-13 at 14 44 42](https://github.com/CrowdDotDev/crowd.dev/assets/20134207/9c7c7767-07a2-473b-931d-38c878b83a71)

<sub>[C-2314](https://linear.app/crowddotdev/issue/C-2314/add-tooltip-to-organizations-identities-in-organizations-list)</sub>

**Comment by peoray** [comment]
picking this up

**Comment by joanagmaia** [comment]
Assigning this one to you @peoray 😄

**Comment by joanagmaia** [comment]
Closing this one @peoray . It was needed in the context of another task
