### ISSUE TITLE
[C-2316] Update "updatedAt" timestamp after a successful check/onboarding

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1497]
> we are running checks mostly every 20min-1h for non webhook integrations
> for discord,discourse and github we are getting data pretty much live -> we are processing them later but still we are getting them without us doing any checks
> for everything else we trigger checks periodically
> what we are missing is triggering an update to the `integrations` table to update `updatedAt` apparently after a successful onboarding/check

At the moment, in the integrations page, we are displaying each connected integration with `last synced <date>` and this date is parsed from `updatedAt`. However, this property is not being updated correctly when there is a new check, so it's showing wrongful information

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2312](https://linear.app/crowddotdev/issue/C-2312/update-updatedat-timestamp-after-a-successful-checkonboarding)</sub>

<sub>[C-2316](https://linear.app/crowddotdev/issue/C-2316/[c-2312]-update-updatedat-timestamp-after-a-successful-checkonboarding)</sub>

**Comment by joanagmaia** [comment]
Hey @yeganathan18 can you try to deploy this one as soon as you have some spare time?

Currently, we are displaying wrong info in the UI so would be cool to prevent having it much longer 😃

**Comment by yeganathan18** [comment]
@joanagmaiagmaia Sure, it's basically done and I just need to ensure that everything works as intended. I'll merge the PR shortly!
