### ISSUE TITLE
[C-2335] Members page - wrong loading state

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1522]
**Steps to reproduce**

1. Go to Merge suggestions page
2. Go back to Members page
3. After the loading spinner, the app renders an empty state of no members before rendering the table

**Expected behaviour**

The empty state for no members should only be displayed when there are indeed no members. Until the request is loaded we should always show the spinner.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2021](https://linear.app/crowddotdev/issue/C-2021/members-page-wrong-loading-state)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2335](https://linear.app/crowddotdev/issue/C-2335/members-page-wrong-loading-state)</sub>

**Comment by peoray** [comment]
picking this up :)

**Comment by joanagmaia** [comment]
Assigned it to you @peoray 😄

**Comment by peoray** [comment]
@joanagmaia is this still an issue? I can't reproduce it

**Comment by joanagmaia** [comment]
@peoray checked it just now and also wasn't able to reproduce it... Gonna close it, and if I'm able to reproduce it I'll reopen this
Thanks!
