### ISSUE TITLE
[C-1246] [C-1247] Custom Views

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1535]
* Reset view
  * If any parameter of a given view was changed the user can reset it to the initial/default state;
* Update view
  * If any parameter of a given view was changed, the user can update it (Save as > Update view):
    * if the view is shared across the workspace, all changes to the view will be applied on all user accounts **(all OOB views are shared across the workspace);**
    * if the view is shared across the workspace, when updated, a confirmation modal is triggered;
    * if the view is not shared across the workspace, only the user account who made the changes will be affected;
    * If the user updates a default view, he can only save it as a new one (”Create new view”). Default views can’t be updated;
* Save as new
  * If any parameter of a given view was changed, the user can update it (Save as > Create new view);
* Add view
  * users can add new views from scratch;
  * new views can be shared (or not) with the workspace;
  * Form fields:
    * View name
    * Display (select box)
      * All members/organizations (including team members/organizations)
      * All members (excluding team members/organizations)
      * Only team members/organizations
    * Include bot members (checkbox): only for Members (disabled for “Only team members”)
    * Filters:
      * All filters available on members or organizations)
    * Sorting
      * All columns available on members or organizations
      * Sort: Ascending or Descending
* Edit view
  * If the view is shared, the user can’t disable this option when editing the view;
  * If the view is not shared, the user can enable the sharing option
  * If the view is shared, when submitting changes, a confirmation modal is triggered;
  * Default views can’t be edited;
* Duplicate view
  * If the user duplicates a view, a drawer will open prefilled with the view settings (view name with a sequential number after)
  * When duplicating a shared view, the user can disable this option;
  * If the user duplicates a shared view, and keeps the sharing option enabled, a confirmation modal is triggered;
  * Default views can’t be duplicated;
* Delete view
  * If the user deletes a shared view, a confirmation modal is triggered and the view will be deleted on all user accounts;
  * If the user deletes a non-shared view, a confirmation modal is also triggered;
  * Default views can’t be deleted;

<sub>[C-1246](https://linear.app/crowddotdev/issue/C-1246/%5Bbackend%5D-ability-to-create-update-and-delete-saved-searches)</sub>
<sub>[C-1247](https://linear.app/crowddotdev/issue/C-1247/%5Bfrontend%5D-ability-to-create-update-and-delete-saved-searches)</sub>

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2359](https://linear.app/crowddotdev/issue/C-2359/[c-1246]-[c-1247]-custom-views)</sub>

**Comment by peoray** [comment]
Seems this is resolved? @yeganathan18

**Comment by yeganathan18** [comment]
Hey @peoray, you're right! the issue no longer exists and I'll close it now 🙂
