### ISSUE TITLE
[C-2295] Add member link in toast message after member creation

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1584]
Add "View member" button to toast message after successfully creating a member.

After editing a member, the app should redirect user to updated member. Toast message does not have any action button in this scenario

<img width="924" alt="Screenshot 2023-09-12 at 14 46 56" src="https://github.com/CrowdDotDev/crowd.dev/assets/20134207/c70c12bd-cc48-4d4c-9223-6b839046025a">

<sub>[C-2295](https://linear.app/crowddotdev/issue/C-2295/add-member-link-in-toast-message-after-member-creation)</sub>

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by joanagmaia** [comment]
> Can I work on this issue?

Of course 😄 Will assign you to the issue

**Comment by peoray** [comment]
picking this up
