### ISSUE TITLE
[C-2116] lastEnrichedAt is not getting updated when we do bulk organizations enrich

### ISSUE THREAD

**Issue by yeganathan18** [CrowdDotDev/crowd.dev#1585]
### Problem

When we enrich organizations of a tenant in bulk through a script, the lastEnrichedAt field is not getting updated.

This is causing the is Enriched filter in the Organizations page not to be functional because lastEnrichedAt is used to check if the organization has been enriched.

### Solution

Make sure that lastEnrichedAt is updated every time an organization is enriched.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2116](https://linear.app/crowddotdev/issue/C-2116/lastenrichedat-is-not-getting-updated-when-we-do-bulk-organizations)</sub>

**Comment by Suraj-kumar00** [comment]
Hi @yeganathan18, How are you doing?
Can I know it more as I'm interested working on this issue.

**Comment by yeganathan18** [comment]
@Suraj-kumar00 Thanks for your interest in contributing! Sorry this issue has been fixed, we highly suggest you check out other good first issues 😄
