### ISSUE TITLE
Only show a preview of the Headline in Organizations list

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1587]
### Problem
In organizations table, the row is growing vertically as much as the height of the `headline` column. Since it's a text field, the attribute can be extensive. We should only show a preview; if the user clicks on the organization, they can see the entire text.

### Solution
If the headline value is bigger than 150 characters, truncate the text.

**Comment by jobayer12** [comment]
@joanagmaia  I would like to work on it. Assign me.

**Comment by joanagmaia** [comment]
> @joanagmaia I would like to work on it. Assign me.

Of course 😄
