### ISSUE TITLE
Hide email under member's identities in member profile if the value is "null"

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1588]
### Problem
In a member's profile page, for some users, an email appears under identities, and it's displayed as "mailto:null".

### Solution
Hide the email under Identities if mail is null since it's clickable and might confuse users. Only display email if not null, undefined, or "".

**Comment by pkd019** [comment]
I want to work on it, please assign me this issue. @joanagmaia

**Comment by joanagmaia** [comment]
> I want to work on it, please assign me this issue. @joanagmaia

Sure 😄 Assigned

**Comment by peoray** [comment]
@joanagmaia  this issue looks to be fixed already

https://github.com/CrowdDotDev/crowd.dev/blob/372d2f2e53fdc419cf7545725eadf83ac51d2225/frontend/src/modules/member/components/view/_aside/_aside-identities.vue#L111

**Comment by joanagmaia** [comment]
> @joanagmaia this issue looks to be fixed already
> 
> https://github.com/CrowdDotDev/crowd.dev/blob/372d2f2e53fdc419cf7545725eadf83ac51d2225/frontend/src/modules/member/components/view/_aside/_aside-identities.vue#L111

Yeah I think you are right. Will close this one, thanks @peoray !
