### ISSUE TITLE
Member search doesn't work if there is a space added

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1592]
### Problem
When searching on the Member page, adding a space after an email results in the Member not showing.

### Proposed solution
We should trim the query string in all pages with search (members, activities and organizations)

**Comment by rutulganatra** [comment]
If no one is working on this then I can work on this?

**Comment by joanagmaia** [comment]
> If no one is working on this then I can work on this?

Yes of course 😄 Assigning it to you

**Comment by joanagmaia** [comment]
@n16htb0t sure

**Comment by peoray** [comment]
picking this up :)
