### ISSUE TITLE
On a Members page, filtering Activity by Platform removes the data

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1595]
### Problem
1. When a user filters activity by platform and there are no results, there is no data shown or empty state below the search bar.
2. There is also no way to remove the filter once it has been selected

### Proposed solution
1. Add a "clearable" button to platform select component so that filter can be cleared and back to the initial state
2. If there are no results from the filter, show an empty state "This member has no activities in "platform name""

![image](https://github.com/CrowdDotDev/crowd.dev/assets/20134207/eec412d7-a22f-4f8c-9cec-da492a2688ca)
![image2](https://github.com/CrowdDotDev/crowd.dev/assets/20134207/c750554d-725b-4c1e-ae18-f7c4eb3824f1)

**Comment by rutulganatra** [comment]
Can you please elaborate this issue?

**Comment by joanagmaia** [comment]
> Can you please elaborate this issue?

Hey!
This is happening in the Activities timeline on the Member profile page.
Just as mentioned in the description, the goal is to improve how we handle with the platform filter. The 2 major goals are:
- If there are no results for the applied filter, show a message
- If user wants to remove the applied filter, we should add a clearable button to the select component -> https://element-plus.org/en-US/component/select.html#clearable-single-select

If this doesn't help, could you be a bit more specific on the doubts you have?

**Comment by AnuMessi10** [comment]
Hi, can I look into this issue? If yes, please feel free to assign it to me. Thanks!

**Comment by krishpatel023** [comment]
Hey, Can you please assisgn me this issue?

**Comment by IAmRiteshKoushik** [comment]
Hey @joanagmaia, I think I should be able to resolve this issue given some time. I have worked on Vue.js code bases before. Can you assign this issue to me ?

**Comment by joanagmaia** [comment]
Hey!
I'm ok with anyone picking this up 😄 Once you do, assign yourself to the issue

**Comment by peoray** [comment]
picking this up
