### ISSUE TITLE
Remove loading animation

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#1596]
### Problem
If the user is already on some page, for example Organizations →  tapping Organizations over and over again keeps showing the loading banned at the top of the screen.

### Proposed solution
Add a validation to the router to prevent showing loading animation if current route and next route are the same. Animation is currently handled in `frontend/src/router/index.js`

**Comment by Sranjan0208** [comment]
Can I work on this issue?

**Comment by joanagmaia** [comment]
> Can I work on this issue?

Of course 😄 
If you need any help let me know

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me
