### ISSUE TITLE
[C-2419] "Enriched organization" filter is broken in organizations

### ISSUE THREAD

**Issue by yeganathan18** [CrowdDotDev/crowd.dev#1634]
Filtering by enriched organization shoots a server error, even though there are clearly organizations in the database.

[Screen Recording 2023-10-06 at 1.37.05 AM.mov](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/f6143aa4-5164-44a9-b7e3-941bc37403d2/2aa784ec-3d5b-4432-82ef-c45e844b6043)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2419](https://linear.app/crowddotdev/issue/C-2419/enriched-organization-filter-is-broken-in-organizations)</sub>

**Comment by peoray** [comment]
Seems this has been fixed
@yeganathan18

**Comment by yeganathan18** [comment]
yes, one of my recent PRs fixed the bug, and sorry forgot to close the ticket.

**Comment by yeganathan18** [comment]
Production QA is also done ✅
