### ISSUE TITLE
Improving README.md of Repository! 

### ISSUE THREAD

**Issue by AaadityaG** [CrowdDotDev/crowd.dev#1656]
### crowd.dev edition

Community (self hosted)

### Link

https://github.com/CrowdDotDev/crowd.dev/blob/main/README.md

### Describe the problem

README.md don't have shield Badges 

### Describe the improvement

![273666603-5b339c4b-9d70-4b9f-bff0-747254d66ea0](https://github.com/CrowdDotDev/crowd.dev/assets/114663382/b495727d-03c9-4429-8099-410339364b47)

**Comment by Gourav2609** [comment]
please assign this to me

**Comment by Ayush-Vish** [comment]
@AaadityaG  @mattinannt  I would like to work on  this issue. Please assign me this issue.

**Comment by joanagmaia** [comment]
@sivangbagri Will try to review it today if I have some time left 😄
