### ISSUE TITLE
Bug Fix - Grammer mistake in Changelog page.

### ISSUE THREAD

**Issue by ayushrakesh** [CrowdDotDev/crowd.dev#1695]
### crowd.dev edition

Community (self hosted)

### What happened?

I have spotted a grammer mistake in Changelog page. Below I have attached the snip of it, you can see , there is double comma after the word "Currently". I want to fix it. 

![Screenshot 2023-10-16 154604](https://github.com/CrowdDotDev/crowd.dev/assets/115995339/01ef37ba-ea0c-4ec4-8484-c4d8a1bfcd39)

### Command / Request

```shell
I want to fix it , please assign this issue to me.
```

**Comment by Ritish134** [comment]
I want to fix it , please assign this issue to me.

**Comment by Ritish134** [comment]
I want to fix it , please assign this issue to me.

**Comment by vinfinity7** [comment]
Hi , can you be more specific as to which file are you pointing to ?

**Comment by Arystar01** [comment]
I want to fix it , please assign this issue to me.

**Comment by vinfinity7** [comment]
@joanagmaia  Kindly review the pr and consider merging under hacktoberfest

**Comment by joanagmaia** [comment]
@vinfinity7 already tagged someone from the team to review it

**Comment by vinfinity7** [comment]
@joanagmaia but that repo doesn't count under hacktoberfest ?
