### ISSUE TITLE
Official web site typo mistake

### ISSUE THREAD

**Issue by AmreeshTyagi** [CrowdDotDev/crowd.dev#173]
### crowd.dev edition

Cloud (hosted)

### What happened?

there is a typo mistake on official website under SECURITY & PRIVACY section on Home page.

Issue: `GDPR & CCPA comliance`

Expected: `GDPR & CCPA compliance`

**Comment by jonathimer** [comment]
Good catch, thanks a lot @AmreeshTyagi! ❤️ 
Just fixed it.
