### ISSUE TITLE
Feature: Scroll to top

### ISSUE THREAD

**Issue by bilalmirza74** [CrowdDotDev/crowd.dev#1768]
### What problem are you trying to solve?

After reaching the footer, instead of scrolling back up by rotating the mouse wheel or swiping on mobile, we can simply click on the scroll-to-top button.

![image](https://github.com/CrowdDotDev/crowd.dev/assets/84387676/294a3e2d-8017-4556-9bb9-d232a3f0a3dc)

### What's your suggested solution?

Adding Scroll to Top Button

### Examples (if relevant)

will be able to scroll to the top in one click

### Is anything blocking this from being implemented? (if relevant)

No

### Definition of Done

UX/UI will be improved

**Comment by themarolt** [comment]
cc @joanagmaia - AFAIK our landing page source code is not pushed to github - it's built using a no-code env like webflow right?
