### ISSUE TITLE
[C-2606] Automatic merging through domains & emails

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1805]
### Describe the Problem

Currently, we have contacts with the same domain, which could be merged automatically.

### Describe the Improvement

Do automatic merging for contacts based on domain & emails.

### Additional Context

For organizations, make sure we are doing the same [Discussion on removal of organizations auto-merge from enrichment](https://crowddevspace.slack.com/archives/C01NBV2BDDK/p1698323968936849)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2606](https://linear.app/crowddotdev/issue/C-2606/automatic-merging-of-domains-and-emails)</sub>

**Comment by jonathimer** [comment]
is this really a "quick win"?
