### ISSUE TITLE
[C-2609] Update default attributes displayed in list views

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1808]
### Describe the Problem

The current attributes displayed in list views are not always populated and often look like we have poor or little data.

### Describe the Improvement

We should think of which attributes make sense to be displayed on the list pages to showcase the most value to the users based on the data we have

**Suggestion:**

**Organizations:**

* New order: Organization, Headline (hide for now), Website, Identities, # of contacts, # of activities, Joined Date, Location, Headcount, Founded, Type, Annual Revenue, Ann. Employee Churn Rate, Ann. Employee Growth Rate, Tags.
  * Imo it makes more sense to give more highlight to Identities. If you’re working without a big screen, you most likely won’t see this column.
  * Remove “Headline” column for now. Due to poor enrichment and cache management, this column is mainly empty and has a massive highlight in the list. I would say to remove it until we have better data.
  * Remove “Emails” column. It’s also mainly empty, and I think users interact with this column sparingly. For instance, it only has 1 click in June.
  * Remove “Employee count” and leave “Headcount” only. I don’t think we should have both. PDL mentions they derive headcount from the company’s self-reported size on their social media profile, so I suggest going with this one.

**Contacts:**

* New order: Contact, Organization & Title, Identities, # of activities, Engagement level, Last activity, Joined Date, # of open source contributions, Emails, Tags
  * Again, for the same reason, we could give more highlights to identities.
  * We should add enrichment attributes to the table -> TBD
  * Remove “Reach”. It’s mainly empty; without Twitter, it’s only populated for GitHub.
  * Remove “# of open source contributions” if the user doesn’t have GitHub connected.

### Additional Context

E.g. Attributes such as Organization's Headline is empty and is displayed as the second column in the list.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-2609](https://linear.app/crowddotdev/issue/C-2609/update-default-attributes-displayed-in-list-views)</sub>

**Comment by peoray** [comment]
is this available for pickup? @nunoeufrasio @joanagmaia

**Comment by joanagmaia** [comment]
Closing this @peoray , as this was fixed in the context of another task
