### ISSUE TITLE
[C-2483] CSV exports - export entire list at once

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1814]
<sub>From [SyncLinear.com](https://synclinear.com) | [C-2483](https://linear.app/crowddotdev/issue/C-2483/csv-exports-export-entire-list-at-once)</sub>

**Comment by primeURL** [comment]
Plz Give more details about the issue. I want to work on this

**Comment by RafaelJohn9** [comment]
see documentation 
![image](https://github.com/CrowdDotDev/crowd.dev/assets/125447154/b769ce9e-c5e8-4092-8e67-d5e8d77845eb)
