### ISSUE TITLE
EagleEye load more shows the same content

### ISSUE THREAD

**Issue by cayden-uw** [CrowdDotDev/crowd.dev#195]
### crowd.dev edition

Cloud (hosted)

### What happened?

I searched for a few terms in EagleEye and had 100+ results found. I got to the bottom of the list and clicked the load more button and the page was refreshed and showed the same results again. 

### Command / Request

```shell
The load more shows the next batch of results
```

**Comment by joanreyero** [comment]
Hi 👋🏼! Thanks for raising this. There is indeed a bug with pagination. We will fix this as soon as possible and report back!

**Comment by cayden-uw** [comment]
Thanks @joanreyero! Loving all the great comms from crowd.dev

**Comment by joanreyero** [comment]
@cayden-uw this should be fixed now 😄 You might need to refresh the page. Thanks again for raising the issue!
