### ISSUE TITLE
Twitter integration keeps disconnecting

### ISSUE THREAD

**Issue by joingardens** [CrowdDotDev/crowd.dev#256]
### crowd.dev edition

Cloud (hosted)

### What happened?

Connected the Twitter integration by following the auth flow in the cloud version. 

Actual behavior: Twitter integration shows "Connected" status initially, but after re-launching the app shows "Failed to connect" and asks to connect again. This happens every time Twitter integration is re-connected

Expected behavior: Twitter integration works, and "Connected" status is displayed in "Integrations" tab, disconnects after several days (?) depending on when the token expires

**Comment by joanreyero** [comment]
Hi! 

Thanks for raising this issue. We are looking into this, and we will report back as soon as we have fixed it. 😄

**Comment by themarolt** [comment]
Hi!

Again @joingardens thank you for reporting this issue - it was pointing to an actual problem in the code which is now solved. I also triggered the processing of your Twitter integration, which went through successfully, so if you log in, you should already see activities and members coming from Twitter.

**Comment by joingardens** [comment]
Great news, thanks!
