### ISSUE TITLE
[C-145] Change all tab titles to match page titles

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#298]
e.g. on [https://app.crowd.dev/members](https://app.crowd.dev/members) the tab should be called "crowd.dev | Members"

<sub>From [SyncLinear.com](https://synclinear.com) | [C-145](https://linear.app/crowddotdev/issue/C-145/change-tab-title-to-match-page-title)</sub>

**Comment by jonathimer** [comment]
*Didier from OpenBB:* 

"Hey man, just noticed that you had 2 different icons on these pages: [https://crowd.dev](https://crowd.dev) and [https://app.crowd.dev](https://app.crowd.dev) Just giving my feedback: I would probably use the same icon and use a separator at the start to differentiate marketing website and the dashboard. For instance: [http://crowd.dev](http://crowd.dev) | The Community-led Growth [http://crowd.dev](http://crowd.dev) Dashboard"

**Comment by yeganathan18** [comment]
I was about to open an issue for the same 👾 something, I noticed right after exploring the platform!

**Comment by jonathimer** [comment]
Yes - it would be definitely an improvement 👀

**Comment by yeganathan18** [comment]
I will work on the issue 😛 probably after completing #773, but if others are interested, they can feel free to take up as well.

**Comment by keshari1arya** [comment]
I am having difficulty to understand @yeganathan18. Is this about the issue?

![Screenshot 2023-04-30 at 7 21 31 PM](https://user-images.githubusercontent.com/16665888/235356671-9648887f-e832-43de-84d2-a64e9dd1c1f5.png)

please feel free to guide me if i am wrong.

**Comment by yeganathan18** [comment]
Hey @keshari1arya thanks for taking up the issue!

### Quick steps to reproduce:

1. Go to this page: https://app.crowd.dev/members (or any other page of your choice)
2. Check the tab in your browser – you'll notice that the page title is "crowd.dev | App" instead of "crowd.dev | Members"

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/63534555/235357132-c3ae5e86-bd0f-47cf-a79c-4483145e20f5.png">

### Possible Fix 

Update the page title to better reflect the content of the page, also it's not just for `Members` but for all the routes. Let me know if you need any further context.

**Comment by keshari1arya** [comment]
Thank you  @yeganathan18 Thank you for describing. Let me have a look.
Please feel free assign me.
Cheers

**Comment by yeganathan18** [comment]
@keshari1arya Have you had a chance to join our [Discord server](http://crowd.dev/discord) yet? We would love to have you there! 🧡

It's a great place to connect with the community, and we do have a special `#contribution` channel where amazing contributors like you, discuss contribution/code related things.

**Comment by keshari1arya** [comment]
Thank you @yeganathan18  for the invite

**Comment by keshari1arya** [comment]
Hey @jonathimer i have created a PR for this enhancement. Kindly have a look and guide me if any refactoring needed.

**Comment by jonathimer** [comment]
Thanks a lot, @keshari1arya! We will review the PR and get back asap 🚀
