### ISSUE TITLE
[C-228] Organizations: remove "# of activities" filter from "new & active" tab

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#300]
![Bildschirmfoto 2022-12-02 um 12.44.03.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/0f6f309c-83e9-4452-8326-ccf6d2f409ec/65813cdf-5172-4bdb-8c84-f77408d19566)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-228](https://linear.app/crowddotdev/issue/C-228/organizations-remove-of-activities-filter-from-new-and-active-tab)</sub>

**Comment by jonathimer** [comment]
@joanreyero shouldnt GitHub issues close automatically? This one is "done" but on GitHub it's still open

**Comment by joanreyero** [comment]
They should… You were the one that connected the GitHub integration. Did you get any notifications?
