### ISSUE TITLE
[C-275] Support string search in the Twitter integration

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#314]
From a user:

*May be good to support multiple hashtags here - even multiple handles would be good. I know that twitter search supports pretty advanced search strings. Maybe just expose the search string and let the user directly use twitter API for the logic?* 

![Screenshot 2022-12-06 at 09.41.45.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/51aa0bce-3f05-4ab2-a583-a4df91f4833b/16d2d7bd-baa5-4549-9818-2920404b0504)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-275](https://linear.app/crowddotdev/issue/C-275/support-string-search-in-the-twitter-integration)</sub>

**Comment by jonathimer** [comment]
perhaps we could add this feature as an "expert mode"

**Comment by jonathimer** [comment]
can be done with Zapier
