### ISSUE TITLE
[C-295] Support cumulative graphs on Reports

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#332]
Currently we only support unaggregated graphs. However, for things like star evolution it could be helpful.

From Discord:
"Is it possible to get a star history graph? I don't think you support any "aggregations or functions" - I'd love to plot: \[cumulative starred\] - \[cumulative unstarred\] (which means the first data point is 0 and the last data point is the current number of GH stars for a project)
Same for pulls, etc. cumulative stats are pretty valuable in a lot of contexts"

---

Created via [Raycast](https://www.raycast.com)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-295](https://linear.app/crowddotdev/issue/C-295/support-cumulative-graphs-on-reports)</sub>

**Comment by jonathimer** [comment]
doable with default reports
