### ISSUE TITLE
[C-296] Repository traffic data

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#333]
To measure the adoption of an OSS project, it would be useful to track traffic data.

* GitHub page view stats: [https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-page-views](https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-page-views)
* GitHub clone stats: [https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-repository-clones](https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-repository-clones)
* GitHub top traffic sources: [https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-top-referral-sources](https://docs.github.com/en/rest/metrics/traffic?apiVersion=2022-11-28#get-top-referral-sources)

Docker Pulls might be more tricky for historical data. For live data, we can use the following:

[https://hub.docker.com/v2/repositories/crowddotdev/backend/](https://hub.docker.com/v2/repositories/crowddotdev/backend/)

## Challenges

These stats are numbers-only. They do not fit our activity/member model. To have it, at least, in the reports section, we will need a new table and new Cubes. This could be a reasonable MVP.

## From Discord

*I know you store activities, so tracking anonymous metrics is not ideal in your data model but hear me out: There is no good solution at all anywhere on the web to easily track and analyze: - GH downloads - GH traffic stats - GH registry image pulls - Docker Hub image pulls. I bet people would pay for someone to scrape these metrics, store them and make them analyzable. Because unlike GH stars, these metrics show real project signals and adoption. I think these metrics would be very powerful on your reports combined with other user-focused metrics.*

<sub>From [SyncLinear.com](https://synclinear.com) | [C-296](https://linear.app/crowddotdev/issue/C-296/repository-traffic-data)</sub>

**Comment by jonathimer** [comment]
this should not be an issue for our data model with template-based reports

I think the challenge is more around getting the data; I don't think you can get it via GH API

**Comment by joanreyero** [comment]
Yes, you can. The endpoints are in the description

**Comment by jonathimer** [comment]
@nuno we should take those data points into consideration for a template-based reports
