### ISSUE TITLE
[C-303] [C-302] Move Discord integration to websockets

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#338]
<sub>From [SyncLinear.com](https://synclinear.com) | [C-302](https://linear.app/crowddotdev/issue/C-302/move-discord-integration-to-websockets)</sub>

<sub>[C-303](https://linear.app/crowddotdev/issue/C-303/[c-302]-move-discord-integration-to-websockets)</sub>

**Comment by joanreyero** [comment]
There are a couple of things I found when doing QA

Replies (non-threaded) are not being caught

* This is in Discord
  * 

    ![Screenshot 2023-02-10 at 15.36.17.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/d2e20576-7b55-425c-b801-4adc1f54b674/de2ab78a-8973-407d-b512-602abc1d1e69)
* This is crowd.dev
  * 

    ![Screenshot 2023-02-10 at 15.36.08.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/77b8c1a8-14fc-47f9-aa08-a921f1121711/2929573e-e1df-4dee-bfac-f28a4100043c)

Thread starters show strange

![Screenshot 2023-02-10 at 15.37.56.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/67c5de75-2752-45bf-9cce-f505eadda8b6/6eacc0b6-f76c-4644-8136-9c61f758c310)

**Comment by jonathimer** [comment]
duplicate
