### ISSUE TITLE
Self-hosting: Access error 

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#42]
### crowd.dev edition

Community (self hosted)

### What happened?
From a user:

Went to the repo (cloned it) and ran the bash script. Got this error.
![3EB0D775423633CA5E6D_0](https://user-images.githubusercontent.com/41432658/188484577-5bee90da-30fc-4239-b422-810afa79962b.jpeg)

I followed the steps here (https://docs.crowd.dev/docs/local-development) and ran into an access error.
![3EB08EDAA6206C9A38750](https://user-images.githubusercontent.com/41432658/188484575-1c14c3f6-f912-4f3f-84ca-3591342b2248.jpeg)

**Comment by epipav** [comment]
all docker images are public now, should be accessible without a problem
