### ISSUE TITLE
[C-482] Organization urls without scheme (`http/https`) render 404 in app

### ISSUE THREAD

**Issue by markphelps** [CrowdDotDev/crowd.dev#429]
### crowd.dev edition

Cloud (hosted)

### What happened?

Clicking on the url of an organization's website where the website doesn't start with `http://` or `https://` acts as an internal app link, which causes a 404 instead of trying to access the external website

Organization URLs that do have `http` or `https` (scheme) in front work correctly

I captured a .gif of this in the app

![Kapture 2023-01-17 at 09 37 27](https://user-images.githubusercontent.com/209477/212927974-acb4543e-dad9-4932-8c43-dfc8a1703795.gif)

Here, your `crowd.dev` org correctly has the `https://` in front, however `perfectscale` does not, so the link location ends up being `https://app.crowd.dev/perfectscale.io` which 404s

<sub>[C-482](https://linear.app/crowddotdev/issue/C-482/organization-urls-without-scheme-httphttps-render-404-in-app)</sub>

**Comment by jonathimer** [comment]
Thanks for the issue @markphelps! We'll look into it.
