### ISSUE TITLE
[C-597] Add attribute: # of open source contributions

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#478]
Add attribute "# of open source contributions". This should appear both in the profile view of each member, the list page (app.crowd.dev/members), and be filterable and sortable. The type is `integer`.

### Member repository

Most of the changes on the backend will be in the `backend/src/database/repositories/memberRepository.ts` file.
In the `findAndCountAll` function, a new aggregator will have to be created. For example:

```
const numberOpenSourceContributions = Sequelize.literal(`jsonb_array_length(“member”.contributions)`)
```

It will also have to be passed to the `QueryParser` accordingly. Fields like `activityCount` and `averageSentiment` will provide a good example. The same should be followed for the number of open-source contributions.

### Tests

The tests will also need to be modified. The affected files will be `memberRepository.test.ts`,  `memberService.test.ts` and `conversationRepository.test.ts`.

### Member Profile

The new attribute for # of open source contributions can be treated in the same way as **# of activities** and **Member since**. These values are displayed in the member profile ([https://app.crowd.dev/members/{id}](https://app.crowd.dev/members/%7Bid%7D)) below the member's name and bio.

To add this new attribute next to the others, the `frontend/src/modules/member/components/view/member-view-header.vue` needs to be updated. The `<template>` should be updated similar to the element of **# of activities**.

### Member Filters

There will be the need to update `frontend/src/modules/member/member-model.js` with the the new filter. The new property of the model needs to be created from an `IntegerField` since the # of open source contributions will be an integer. The `IntegerField` should then be configured with an **identifier**, a **label**, and an **options** object (filterable should be set to true).

<sub>From [SyncLinear.com](https://synclinear.com) | [C-597](https://linear.app/crowddotdev/issue/C-597/add-attribute-of-open-source-contributions)</sub>

**Comment by aryanvarma7272** [comment]
Hey @jonathimer , can you elaborate what has to be done ? I am a beginner and very eager to work on this issue!

**Comment by jonathimer** [comment]
Hey @aryanvarma7272, thanks for reaching out. We're happy to assist you with this issue.

I'll get back asap with more concrete specs. If you want, we'd also do a [quick onboarding call](https://cal.com/team/CrowdDotDev/contributor-onboarding) and give you an intro to our codebase and the particular task.

**Comment by joanreyero** [comment]
Hey @aryanvarma7272, thanks for your interest in contributing! I have updated the task description with front-end and back-end specifications and tips. As @jonathimer said, super happy to give you an onboarding call to get you up and running! 🚀
