### ISSUE TITLE
[C-612] "Delete Workspace" functionality

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#485]
We should give users the option to delete their workspaces (as admin users)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-612](https://linear.app/crowddotdev/issue/C-612/delete-workspace-functionality)</sub>

**Comment by keshari1arya** [comment]
Hey @jonathimer,
kindly provide a little more details.
do you mean deleting organisation when you say workplace?
