### ISSUE TITLE
[C-618] Default report URL should be "/reports/default" not "/reports/template"

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#489]
we decided to change the terminology and should do this consistently across the product too

see: "[https://app.crowd.dev/reports/template](https://app.crowd.dev/reports/template)"

**Steps to achieve this:**

* In `report-routes.js` there is an entry for this route. The `path`should be updated to `/reports/default/:id`

Check if we need to redirect any route to the new one to prevent inaccessible links

<sub>From [SyncLinear.com](https://synclinear.com) | [C-618](https://linear.app/crowddotdev/issue/C-618/default-report-url-should-be-reportsdefault-not-reportstemplate)</sub>

**Comment by a0m0rajab** [comment]
Hi is this issue is still relevant? 

I checked `report-routes` the path it's being used right now as `templates` should the template be default? 

https://github.com/CrowdDotDev/crowd.dev/blob/d8135bcdf1fda886904cb59048e6043c956c8d2c/frontend/src/modules/report/report-routes.js#L31-L61

**Comment by joanagmaia** [comment]
Hey @a0m0rajab!
Yeah it is 😄 
And yes `template` should be `default`

**Comment by peoray** [comment]
@a0m0rajab 🙂 are you working on this? If not, I can pick this up

**Comment by a0m0rajab** [comment]
@peoray thank you for the head up, yes I was postponing for local development set up. 
@joanagmaia Thank you for the information, really appreciate it.

**Comment by peoray** [comment]
sure thing👍🏾. if you need setting up, lemme know. had my own fair share of issues setting up the project 😀

**Comment by a0m0rajab** [comment]
Thank you for the offer, to be honest I went with the short path here: `github.dev` 😄

**Comment by peoray** [comment]
Fairs😀. This is probably the easiest pr ever😁

**Comment by a0m0rajab** [comment]
Lol, did not notice that till now. It's my first PR in this project.
