### ISSUE TITLE
[C-626] Add organization + title to member search in merge members view

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#502]
From a user:

"Searching for merging members is a pain. The autocomplete will give you only the name, no preview like avatar, only 10 in the autocomplete, leading to the member page and searching the exact members' name."

This is not the normal search, but for example when searching for members to merge

## Solution

We should have a better search. We should show the avatar and organization (just name).

<sub>From [SyncLinear.com](https://synclinear.com) | [C-626](https://linear.app/crowddotdev/issue/C-626/improve-member-search-in-merge-members)</sub>

**Comment by jonathimer** [comment]
only organization name missing
