### ISSUE TITLE
[C-627] Make Location a multi-select field

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#503]
From a user:
"Company is only a text field with no auto-completion. I would like to have proper autocompletion. Same for Location."

For this, we would need to make Location a multi-select field. This will require some modification for our data:

* For each tenant:
  * Get all locationds and add them as options

<sub>From [SyncLinear.com](https://synclinear.com) | [C-627](https://linear.app/crowddotdev/issue/C-627/make-location-a-multi-select-field)</sub>

**Comment by jonathimer** [comment]
after this, we can easily to [C-587](https://linear.app/crowddotdev/issue/C-587/display-members-by-location-on-a-world-map)

**Comment by joanagmaia** [comment]
@joanreyero currently both Members and Organizations have a Location field. Will these changes only impact Members or also Organizations?

@anil at the moment we are also using `Members.location` as a dimension in Custom reports. Just warning about this as I'm not sure if this issue will also require some update in Cube

**Comment by joanreyero** [comment]
Good points 🙏

I think we can start with members first
