### ISSUE TITLE
Start don't show on Neovim

### ISSUE THREAD

**Issue by Antosser** [CrowdDotDev/crowd.dev#519]
### crowd.dev edition

Community (self hosted)

### Version

the hosted one

### What happened?

![image](https://user-images.githubusercontent.com/71790328/218253088-77893cbd-c5d3-446f-abcf-a5e43896caaa.png)
For some reason, the stars on Neovim don't show, putting it at the bottom of the list when it should be at the top.

**Comment by garrrikkotua** [comment]
Hey @Antosser,

Thanks for noticing this! It is fixed now 😃 

Let us know if you find any other bugs.
