### ISSUE TITLE
[C-672] User's organization is showing as the most active one

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#520]
Reported through formbricks:

> In the weekly report, it shows my own company (Kestra) on top of the most active organizations. That shouldn't be the case.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-672](https://linear.app/crowddotdev/issue/C-672/users-organization-is-showing-as-the-most-active-one)</sub>

**Comment by jonathimer** [comment]
by Tanay Pant (Kestra)
