### ISSUE TITLE
[C-728] Review YouTube integration

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#544]
# crowd.dev <> YouTube Integration

## Problem Statement

An integration to fetch activities from YouTube based on channels and keywords/hashtags.

## Why

The YouTube integration will enable our users to monitor videos and comments from YouTube channels or based on specific hashtags and keywords. This will help users to track the activities and engagement of their audience on YouTube.

## What

The YouTube integration will have two modes:

1.  Channel-based: Fetch all videos and comments from corresponding channels.
2.  Hashtags/Keywords-based: Fetch all videos and comments with matching hashtags or keywords from any channel.

In this integration, we will create a member from any user who commented on a video. The only activity to track is user comments.

## How

We'll create a `youtubeIntegrationService.ts` where we will encapsulate all the logic related to fetching data from YouTube.

### Authentication

YouTube API uses OAuth 2.0 for authentication. We'll ask the user to authenticate with their Google account, and our application will use the OAuth 2.0 credentials to access the YouTube Data API. YouTube relies on Google's OAuth.

We should use Nango's Goolge template for this as we do with other integrations (e.g StackOverflow, Reddit). Docs for nango [here](https://docs.nango.dev/providers/google) and [here](https://docs.nango.dev/providers/youtube)

***crowd.dev internal team:*** need to setup a **Google Cloud Platform project**

### API Endpoints

-   [Search API](https://developers.google.com/youtube/v3/docs/search): To fetch videos based on channel ID or hashtags/keywords.
-   [Channels API](https://developers.google.com/youtube/v3/docs/channels): To fetch the channel details.
-   [Comments API](https://developers.google.com/youtube/v3/docs/comments): To fetch comments on videos.

### Integration Workflow

The suggested workflow is as follows:

1.  User authenticates with their Google account and grants permissions to our application.
2.  Based on the mode selected by the user (channel-based or hashtags/keywords-based), we use the Search API to fetch videos. This is configured on the frontend.
3.  For each video, we fetch the comments using the Comments API.
4.  We create a member for each user who commented on the video and track the comment activity.

## Tasks

-   Implement the backend and frontend components for the YouTube integration.
-   Set up OAuth 2.0 for YouTube API (using Nango)
-   Implement the channel-based and hashtags/keywords-based modes.
-   Fetch videos and comments data from YouTube.

**Comment by jonathimer** [comment]
If you need help you can reach us either via [Discord](http://crowd.dev/discord) or [Book a Contributor Onboarding Call](https://cal.com/team/CrowdDotDev/contributor-onboarding?duration=15).

**Comment by logicncode** [comment]
Hi @jonathimer 
I would like to work on this!
Can you please assign this to me?

**Comment by keshari1arya** [comment]
Is this open and unassigned @jonathimer ?

**Comment by jonathimer** [comment]
Hey @keshari1arya, yes this issue is still open. Do you want to tackle it?

**Comment by keshari1arya** [comment]
Hey @jonathimer,
Oh yeah, i will be happy to be a part of it.

**Comment by jonathimer** [comment]
Awesome! It's a bigger project so please let us know on Discord if you need any help.

**Comment by keshari1arya** [comment]
Thank you @jonathimer.

**Comment by Shurtu-gal** [comment]
@jonathimer, is this still open for the taking?

**Comment by keshari1arya** [comment]
@Shurtu-gal i am little occupied now please feel free to continue on this.

**Comment by Shurtu-gal** [comment]
Sure, let me see what I can whip up.

**Comment by debaa98** [comment]
is this issue is still open?

**Comment by vickywane** [comment]
@jonathimer 

I'm interested in working on this issue.

**Comment by jonathimer** [comment]
Hey! The issue is still open. :) 

Please feel free to reach out on Discord if you need any help.

**Comment by vickywane** [comment]
@jonathimer 

Thank you. 
I will reach out on Discord.

**Comment by keshari1arya** [comment]
My dear Mates,
I was wondering if anyone has already started working on this item? If not, I'd like to offer my assistance, and I'm open to collaborating as a team if anyone is interested.

Please feel free to reach out if you need any help or if you'd like to work together on this project. Your input and collaboration are highly valued.

**Comment by Shurtu-gal** [comment]
> My dear Mates, I was wondering if anyone has already started working on this item? If not, I'd like to offer my assistance, and I'm open to collaborating as a team if anyone is interested.
> 
> Please feel free to reach out if you need any help or if you'd like to work together on this project. Your input and collaboration are highly valued.

Yeah, I have started somewhat but facing problems in local setup. We can connect and discuss it I guess.

**Comment by mrteey** [comment]
Can I still work on this? If yes, is there any specific stack for the backend?

**Comment by ologbonowiwi** [comment]
@jonathimer, what if we split this issue into other issues?

The first would be to authenticate with Google (cause this is a blocker to all others), and then we can parallelize the other tasks; what do you think?
