### ISSUE TITLE
[C-787] Typo in default report Members

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#567]
![Bildschirmfoto 2023-02-23 um 16.01.58.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/774dcdce-14e2-4190-9534-8f9edc2aa23e/fb11a578-7bde-4602-b648-e49cbc5f05bd)

→ **Leaderboard**

<sub>From [SyncLinear.com](https://synclinear.com) | [C-787](https://linear.app/crowddotdev/issue/C-787/typo-in-default-report-members)</sub>

**Comment by peoray** [comment]
<img width="1426" alt="Screen Shot 2023-04-13 at 12 35 06 AM" src="https://user-images.githubusercontent.com/23735423/231608534-9f6de0f3-91f6-4b03-a1b9-f17c251dff17.png">

@jonathimer I get this error after running the script command
