### ISSUE TITLE
[C-37] Email for Slack and Discord integrations

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#589]
When someone sets up Slack and Discord, we should send an email that explains how to set it up

<sub>From [SyncLinear.com](https://synclinear.com) | [C-37](https://linear.app/crowddotdev/issue/C-37/email-for-slack-and-discord-integrations)</sub>

**Comment by joanreyero** [comment]
agree

an email should only happen if the user missed some step in the process

**Comment by joanreyero** [comment]
I think we should retain users in-app as much as possible, and provide the guidance they may need, when they need it, without breaking the journey or expecting they are going to check their inbox in the middle of the onboarding process

cc @jonathimer

**Comment by jonathimer** [comment]
i believe this is kind of finished?
