### ISSUE TITLE
[C-815] Keep multiple identities when merging members

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#592]
**Problem**

If two members get merged, identities that exist in both members get overwritten (if they differ).

**Solution**

We store handles in an array attribute `alternativeIdentities` so they don't get lost.

```
{
  "github": ["gh_i1", "gh_i2",...]
  "email": ["email1", "email2"...]
  "discord": ...
}
```

<sub>From [SyncLinear.com](https://synclinear.com) | [C-815](https://linear.app/crowddotdev/issue/C-815/keep-multiple-identities-when-merging-members)</sub>

**Comment by joanreyero** [comment]
Emails are in the other issue, better specified. I will remove them from the issue.

**Comment by jonathimer** [comment]
do we have a ETA for this?

**Comment by joanreyero** [comment]
End of this week best case, middle of next week worst-case

**Comment by jonathimer** [comment]
how can that happen? shouldn't activities be assigned automatically vs creating a new member with the same GH handle?

**Comment by joanreyero** [comment]
Let's not put it on Done until it's deployed on Thursday
