### ISSUE TITLE
[C-846] Eagle Eye email digest has wrong settings

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#612]
**Daily Digest**

currently: everyday (also weekend), time frame settings from feed

should be: Monday to Friday, Last 24 hours

**Weekly Digest**

currently: to be checked

should be: Monday, Last 7 days

<sub>From [SyncLinear.com](https://synclinear.com) | [C-846](https://linear.app/crowddotdev/issue/C-846/eagle-eye-email-digest)</sub>

**Comment by peoray** [comment]
@jonathimer can you provide more context on this issue?

**Comment by peoray** [comment]
Hi, @jonathimer can you provide more context on this issue?

**Comment by jonathimer** [comment]
Hey @peoray!

The user can set up a email digest to receive the results from Eagle Eye (/eagle-eye). 

**Currently**
Daily email digest is sent everyday (also weekend) with the time frame settings from feed


**Expected behavior**
Daily email digest should be sent only Monday to Friday and always display the results from the last 24 days (not taking into account the settings of the feed)

**Comment by peoray** [comment]
what do you mean by not taking in the settings on the feed

**Comment by peoray** [comment]
Oh I understand now (wouldn't mind your explanation though just to be safe).

To clarify, does the get request return more than this and you want the frontend to limit it to just 24 days?

**Comment by jonathimer** [comment]
Currently, the email digest takes the time period set in the "feed settings" - here displayed as "published date"

<img width="2550" alt="Bildschirmfoto 2023-04-23 um 12 58 46" src="https://user-images.githubusercontent.com/41432658/233835943-4b7982c4-3c9f-42e2-b57c-bfcd26e8cc48.png">

The daily email digest should always display results from the last 24 hours. :)

**Comment by jonathimer** [comment]
The web app should still display it according to the feed settings.

But the email digest (that you get to your email inbox) should only display the last 24 hours.

**Comment by peoray** [comment]
@jonathimer thank you
Pardon me, I like to be always clarify :)

I know you said 24 days before but based on this new information, I guess that was a mistake :D

Based on the instructions, essentially my task is to ensure the daily digest (which is what get sents to your mail) is from Monday to Friday and then only show results from the last 24hrs?

So this ignores the settings of the feed which is also what controls the web app. I just need to give daily digest a new set of instructions to follow

**Comment by peoray** [comment]
@jonathimer thank you
Pardon me, I like to be always clarify :)

I know you said 24 days before but based on this new information, I guess that was a mistake :D

Based on the instructions, essentially my task is to ensure the daily digest (which is what get sents to your mail) is from Monday to Friday and then only show results from the last 24hrs?

So this ignores the settings of the feed which is also what controls the web app. I just need to give daily digest a new set of instructions to follow

**Comment by peoray** [comment]
@joanagmaia can you clarify my last statement?

**Comment by peoray** [comment]
<img width="1432" alt="Screen Shot 2023-04-26 at 2 13 19 PM" src="https://user-images.githubusercontent.com/23735423/234586021-9532049b-a467-40c9-9a5b-75abae8fe926.png">
