### ISSUE TITLE
[C-848] Eagle Eye: ignore post if there is no date

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#615]
When there is no date, we are currently using the current date. This is causing the post to be re-shown time after time, even if it's old. We should just ignore the post.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-848](https://linear.app/crowddotdev/issue/C-848/eagle-eye-ignore-post-if-there-is-no-date)</sub>

**Comment by jonathimer** [comment]
how many posts will be excluded by this?

we already don't find too many

**Comment by joanreyero** [comment]
Less than 10%

But I don't see another solution. Otherwise posts with no date will always be there

**Comment by peoray** [comment]
@joanagmaia @joanreyero is this still open for contribution?

**Comment by joanreyero** [comment]
Hey Emanuel! Thanks for the offer! However, this issue should be closed. This was already fixed. Closing it now.
