### ISSUE TITLE
[C-870] Missing file openapi.json

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#631]
### crowd.dev edition

Community (self hosted)

### Version

Frontend - 0.5.0

### What happened?

Hello,

Cloned the code on local and while building the code on local, it is giving error for openapi
Found out that the file 'openapi.json' is missing.

After further looking at the code found out that the file is present at following location '/backend/src/documentation' but the  name is 'openapi copy.json'

Please rename the file 'openapi copy.json' to 'openapi.json'

Thank you!

<sub>[C-870](https://linear.app/crowddotdev/issue/C-870/missing-file-openapijson)</sub>

**Comment by jonathimer** [comment]
Hey @RaginiAngarka, Thanks for opening an issue. We'll take care of this asap.
