### ISSUE TITLE
git describe "fatal: No names found, cannot describe anything."

### ISSUE THREAD

**Issue by rodrigorivera** [CrowdDotDev/crowd.dev#66]
### crowd.dev edition

Community (self hosted)

### What happened?

I did a fork without the various branches. I am trying to run the repository following the instructions. However, while executing `bash start.sh`, I get as an output `fatal: No names found, cannot describe anything.`

A quick search on SO shows that this is connected to git describe. I see you have
`CROWD_VERSION="$(cd $CLI_HOME && git describe --tags --abbrev=0)"`

Is it necessary to use git describe like that?  I see you require this to grab the right docker version, but why not hardcode it to the stable release for deployment and the latest one for development?

### Command / Request

```shell
bash start.sh
```

### Relevant log output

```shell
crowd.dev$ bash start.sh
fatal: No names found, cannot describe anything.
```

**Comment by joanreyero** [comment]
Hi @rodrigorivera 👋🏼

Thanks for raising this! We are working on a complete architecture revamp that will use Kubernetes, which will (most likely) be deployed on Monday. The new architecture will be much simpler, especially for local development. `git describe` will not be necessary then 😄

I will follow up on this once the new architecture is up and running!

**Comment by joanreyero** [comment]
Hi @rodrigorivera 

We have a whole new way to start the development environment! You can check it out [here](https://linear.app/crowddotdev/issue/C-11/automatically-generated-tags). Closing this and [the other development environment issues](https://github.com/CrowdDotDev/crowd.dev/issues/66) for now!
