### ISSUE TITLE
[C-964] Missing to parse member's bio in Merge Members Suggestions page

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#675]
**Problem**

Currently, in the Merge Members Suggestions page, the member's bio is not being parsed as html. It's displaying the content as plain text.

**Solution**

In `member-merge-suggestions-page.vue` the code to display `scope.row.attributes.bio` should be using the newly created component `member-bio.vue` . This one has the logic to parse the content.

Suggestion: I think we should also limit the number of characters that is displayed (I believe this is not implemented right now). For example, we could use a "Show more"/"Show less" button below the bio to expand/collapse content if it overflows x characters

<sub>From [SyncLinear.com](https://synclinear.com) | [C-964](https://linear.app/crowddotdev/issue/C-964/missing-to-parse-members-bio-in-merge-members-suggestions-page)</sub>

**Comment by peoray** [comment]
hello, @joanagmaia just discovered this project :). Is this open for contribution?
