### ISSUE TITLE
[C-1072] [C-1073] Keep timeframe in default reports URL

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#712]
from Discord (#support): _Members report is quite useful, though it would be great to keep selected timeframes (1y, 6m, etc) in the private/public report URL to simplify sharing._

<sub>[C-1073](https://linear.app/crowddotdev/issue/C-1073/keep-timeframe-in-members-report-url)</sub>

## Description

- Each widget should have its URL timeframe. If the widget has granularity, it should also be kept in the URL.
- There should be a global platform filter also in the URL

It should be done in the Members report, Product-community-fit report and the activities report.

**Comment by jonathimer** [comment]
definition of done:
- store the selected timeframes in reports URL so users can share reports including pre-selected timeframes

**Comment by orimdominic** [comment]
Hello @jonathimer I'll like to take up this issue.
Is there any other thing that I should know apart from what has been stated in the comments under this issue?
Thanks.

**Comment by jonathimer** [comment]
Awesome, I just assigned the issue to you!

- All filter settings (platforms, team member) and time selections should be reflected in the URL (if not the default ones).
- This should be implemented for both the Members & Product-Community Fit report 

Let me know if you have any questions. You can also [join our Discord.](http://crowd.dev/discord)

**Comment by peoray** [comment]
Is this still available for pickup? @jonathimer

**Comment by orimdominic** [comment]
@peoray please pick it up. I'm afraid I've been too busy to submit a PR.
I've only done part of it 🙏

**Comment by yeganathan18** [comment]
Hey, @peoray! Do you need any more help from our side to tackle the issue? 😄

**Comment by peoray** [comment]
@yeganathan18 yeah, I'll write down my work so far and probably send in a draft PR as soon as I can

**Comment by yeganathan18** [comment]
Sounds good 👍

**Comment by Pradumn27** [comment]
Hey @jonathimer I'd like to pick this up, I don't see much activity here.

**Comment by yeganathan18** [comment]
Hey @Pradumn27! Thanks for your interest in contributing! 

Feel free to pick the issue and if you need any help, let us know :)
