### ISSUE TITLE
[C-1154] Update API Documentation

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#736]
### crowd.dev edition

Cloud (hosted)

### What happened?

Few observations while trying to run the APIs. Please update the documentation, so it helps other developers. 
Following  are the observations:-
 
1. List Active Members (https://docs.crowd.dev/reference/get_tenant-tenantid-member-active) :-
According to the API documentation, the parameter name should be "filter[activityTimestampFrom]."
But when API is called, it gives an error :- as‘activityTimestampFrom’ is a required parameter. 
Please update the API error code. 
It should be 'filter[activityTimestampFrom]' and not ‘activityTimestampFrom’.
 
The documentation says the API is expecting a timestamp, but when timestamp is passed, the API gives an error as ‘date’ field out of range. After a few tries, I understood that it accepts the parameter in YYYY/MM/DD format. After sending the date in YYYY/MM/DD format, it works fine, but if we send YYYY/DD/MM then it gives an error as‘date’ field out of range.`
Please update documentation with expected format of the timestamp.
 
2. QueryOrganizations (https://docs.crowd.dev/reference/post_tenant-tenantid-organization-query) :- 
The newly created organization is not getting listed. Once the member is assigned to Organization then Organization is getting listed in Organizations list. Is that expected? If yes, then please update the documentation, otherwise the developer has no clue why it is not getting listed.
 
3.  Update Member API (PUT) (https://docs.crowd.dev/reference/put_tenant-tenantid-member-id):-
Is not allowing to assign member to an Organization. It is giving error - Invalid value { name: 'XXX' }.  Please update documentation with correct field name.

<img width="1044" alt="Screenshot 2023-04-10 at 1 56 38 PM" src="https://user-images.githubusercontent.com/87848481/230864001-c22c98c3-3831-43f6-b0aa-3ae31a3b47c6.png">

 
There is another method Update Member (https://docs.crowd.dev/reference/post_tenant-tenantid-member) (POST), with this API, could assign member to Organization. 
Is this correct method to update member data?  Is yes, then please update the documentation for Update Member API (PUT) accordingly. 
 
4. Create or update an activity (https://docs.crowd.dev/reference/post_tenant-tenantid-activity) (POST):-
Even though ‘memberId’ is passed, it is giving error as - notNull Violation: activity.memberId cannot be null. Please update documentation with appropriate parameter name.  
Please provide a link to the list of activity types in the doc. 
Also, please provide the format which is allowed for 'timestamp' parameter for this API.

<img width="968" alt="Screenshot 2023-04-10 at 1 40 23 PM" src="https://user-images.githubusercontent.com/87848481/230858420-224c0be1-0950-4995-88a3-66b9356278eb.png">

<sub>[C-1154](https://linear.app/crowddotdev/issue/C-1154/update-api-documentation)</sub>

**Comment by jonathimer** [comment]
Thanks a lot for this feedback @RaginiAngarka! 

We will take a look at it and update the documentation accordingly.

**Comment by joanagmaia** [comment]
@joanreyero2reyero moved this one into the following cycle since you won't be here for these remaining days.

Do you think you can prioritize it next week?

**Comment by joanreyero** [comment]
I will try. But I only have 3 days again next week, since we have the strategy offsite

**Comment by RaginiAngarka** [comment]
@joanreyero , can we please update the documentation of this API as well?  Thanks
`PUT` method `https://cm.lfx.dev/api/tenant/{tenantId}/member/{memberId}` 

Related ticket - `https://github.com/CrowdDotDev/linux-foundation-support/discussions/298
`

**Comment by VishavSingla** [comment]
Hi, I am a beginner in open source. Can you assign me this issue?
