### ISSUE TITLE
[C-1195] Github integration : fetch discussion 

### ISSUE THREAD

**Issue by tchiotludo** [CrowdDotDev/crowd.dev#746]
Actually github discussion are not fetched by the github integration. 
Since github discussion is more and more popular, we need to track them as github issues

<sub>[C-1195](https://linear.app/crowddotdev/issue/C-1195/github-integration-fetch-discussion)</sub>

**Comment by Charlotte0709** [comment]
Hi @tchiotludo, thanks for pointing this out. We should be fetching GitHub discussions already, we will check this out and get back to you

**Comment by joanreyero** [comment]
duplicate

**Comment by jonathimer** [comment]
@tchiotludo FYI: this should be fixed next week :)

**Comment by jonathimer** [comment]
this should be fixed now @tchiotludo!
