### ISSUE TITLE
Merge members : image for merged members are kept and not the one from primary

### ISSUE THREAD

**Issue by tchiotludo** [CrowdDotDev/crowd.dev#748]
### crowd.dev edition

Cloud (hosted)

### What happened?

When you merge a member, it's not the primary image that is kept but the merged one.

**Comment by Charlotte0709** [comment]
Hey @tchiotludo, thanks for bringing this up, we will investigate this. Could you share the member ID (which you can find in the URL of the member profile) where this happened? Thank you!

**Comment by tchiotludo** [comment]
This one `499297fa-d8ca-478d-bf49-25aa8b02d1b1` just now

**Comment by Charlotte0709** [comment]
Thanks! We will check

**Comment by joanreyero** [comment]
Hey @tchiotludo! Thanks for raising the issue. 

The `avatarUrl` is kept for all platforms when merging members. We are displaying based on the priority of the different platforms. In this case, we have an avatar for GitHub and one for Slack, and we are displaying the GitHub one.

In the future, we plan to let users choose this priority. I have created an [issue for this](https://github.com/CrowdDotDev/crowd.dev/issues/757).

Is it a big blocker for you?
