### ISSUE TITLE
[C-860] "Total numbers" on Home don't get affected by platform selection

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#752]
when selecting a platform, the "total numbers" on Home don't get affected

![Bildschirmfoto 2023-03-07 um 10.57.32.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/ba758645-29bd-4ecf-84e6-849e6847775d/ec9d9071-ab14-4755-a5c6-e2f004bb225d)

depending on which platforms are selected by the user, the total # should change

e.g. if only Discord is selected, you should see total members + total activities in Discord

<sub>From [SyncLinear.com](https://synclinear.com) | [C-860](https://linear.app/crowddotdev/issue/C-860/total-numbers-on-home-dont-get-affected-by-platform-selection)</sub>

**Comment by peoray** [comment]
@jonathimer can you provide more information on this

**Comment by jonathimer** [comment]
Hey @peoray, sorry for my slowish response, missed this somehow.

**Problem**
To reproduce this bug, you have to go to the Home of the app and play around with the platform filter. The "total" KPIs next to Members and Activities should change if the platform selection changes.
e.g. if you only select Discord, you should see the total numbers of members active on Discord
currently its always displaying the # of all members in the community

**Solution**
"Total: X" with X being # of Members or Activities should consider the platform selection

Does that make it more clear? :)

**Comment by peoray** [comment]
@jonathimer Thank you, that was helpful. Do I have to update this from the API query or is this done on the FE?

Btw, I can't see the option for the platform on my own page
<img width="1432" alt="Screen Shot 2023-04-18 at 10 56 26 AM" src="https://user-images.githubusercontent.com/23735423/232742276-d0a222db-1ff6-435f-ba38-47ed1c43c6c5.png">

**Comment by jonathimer** [comment]
@gaspergrom can you help? is this purely FE?

I think you can't see the platform filter because you only connected one platform. Add another (e.g. Hacker News) and it should show up.

**Comment by peoray** [comment]
Yeah, I just figured that out. However, it's difficult to add integrations that use oAuth on localhost like Github, Twitter, and Reddit. How do I resolve this

**Comment by jonathimer** [comment]
Hacker News also doesn't require OAuth so it should be easy to set-up.

**Comment by peoray** [comment]
Thanks, that works!

**Comment by peoray** [comment]
@jonathimer how can I view the docs for the API? Maybe like Swagger or similar?

**Comment by peoray** [comment]
@jonathimer does this issue still exist?

**Comment by jonathimer** [comment]
sorry, our GitHub/Linear sync is re-opening them sometimes...
