### ISSUE TITLE
[C-1165] Home: "# of Activities" of Active Members doesn't change based on the time selection

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#755]
![Bildschirmfoto 2023-04-13 um 11.37.33.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/0646dfb3-d19d-4c3e-9a92-5b2687a2d6f2/986971d1-8858-4d27-b307-83859878820b)

currently: "# of Activities" of Active Members doesn't change based on the time selection

expected behavior: "# of Activities" of Active Members should change based on which time frame the user selects (7d/14d/30d). Only activities in the respective time frame should be counted.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1165](https://linear.app/crowddotdev/issue/C-1165/home-of-activities-of-active-members-doesnt-change-based-on-the-time)</sub>

**Comment by yeganathan18** [comment]
Hey, shall I take up this issue?

**Comment by yeganathan18** [comment]
It looks like there is no issue with the component or must be already fixed, I have attached video below 👇

https://user-images.githubusercontent.com/63534555/232207662-33b82bbd-947e-482b-9a94-0210f1c7949a.mov


@jonathimer Let me know what you think!

**Comment by jonathimer** [comment]
Hey, Thanks for picking this up! The issue is that this KPI should only refer to the # of activities that happened within the last 7, 14 or 30 days. As you can see, it e.g. always shows 27 activities for Richard Hendricks (but that would only be the case if Richard did all his activities in the last 7 days)

i can record you a Loom later, if its not super clear :)

**Comment by yeganathan18** [comment]
@jonathimer Got it! Is there any way to verify how many activities does the Richard Hendricks did in past specifically on the time period?

**Comment by jonathimer** [comment]
Yes, you can check it by clicking on his member profile. This will show you all his activities in a feed.

**Comment by yeganathan18** [comment]
@jonathimer can we close this issue? The PR for the same has been merged 🚢
