### ISSUE TITLE
[C-1169] Cloning repo leads to error

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#758]
### crowd.dev edition

Community (self hosted)

### What happened?

from Discord: "Has anyone tried to clone the repo before? Got this error"

![Screen_Shot_2023-04-13_at_12 35 06_AM](https://user-images.githubusercontent.com/41432658/231772948-48f0badb-9f50-4a4a-b1c7-01daf8a5cd56.png)

<sub>[C-1169](https://linear.app/crowddotdev/issue/C-1169/cloning-repo-leads-to-error)</sub>

**Comment by peoray** [comment]
This occurs after running the script command
`./cli clean-start-dev`

**Comment by jonathimer** [comment]
It seems like something else is already running on port 5432 which is the default port for the postgresql db.

I'd recommend to first stop the other service (which is probably another db running locally) and than try it again.

**Comment by peoray** [comment]
I checked nothing is running. Even tried to kill the port but got an error that the port isn't running. Weird
