### ISSUE TITLE
Update member API not working

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#762]
### crowd.dev edition

Cloud (hosted)

### What happened?

When trying to update member's organization with API (PUT method)- https://docs.crowd.dev/reference/put_tenant-tenantid-member-id it is not working.
It is giving error as Invalid value { name: XX}

<img width="1039" alt="Screenshot 2023-04-14 at 12 43 34 PM" src="https://user-images.githubusercontent.com/87848481/231971168-68c6acd5-7ab4-4888-bb0e-9ff951bdb54a.png">

**Comment by Charlotte0709** [comment]
Thanks for letting us know @RaginiAngarka!

We will take a look at this.

**Comment by joanreyero** [comment]
Hey @RaginiAngarka 

Thanks for raising this!

Our apologies; there was an error in the docs. I just fixed it.

The update method only takes the IDs of the relations. You have to send the organization's ID there. Otherwise, you can use the upsert method for sending the full organization.
