### ISSUE TITLE
[C-1196] Add link to signup from sign-in page

### ISSUE THREAD

**Issue by yeganathan18** [CrowdDotDev/crowd.dev#766]
## Describe the problem

Currently, if someone (potentially a new user) landed our sign-in page, then there is no link to redirect the user to signup. It creates a small confusion – _where should I sign up now?_

<img width="1792" alt="Screenshot 2023-04-15 at 4 04 52 PM" src="https://user-images.githubusercontent.com/63534555/232208843-f3696d1e-af16-4c87-ae49-55ba65c22d27.png">

## Describe the improvement

We should consider adding a signup link somewhere in the sign-in page so that the user is not diverted with the process.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/63534555/232209244-f0c14a6d-b5df-4bd1-a5cf-9fc4902d3477.png">

(random example from supabase sign-in page)
## Additional context

Trust me, sometimes we open GitHub issue based on the personal experience 🛸

<sub>[C-1196](https://linear.app/crowddotdev/issue/C-1196/add-link-to-signup-from-sign-in-page)</sub>

**Comment by jonathimer** [comment]
ohh that's a good one - I think it comes from the time when we were in closed beta 😅 should definitely add this asap

Thanks for pointing it out!

**Comment by yeganathan18** [comment]
@jonathimer cool, no worries! I was bit into CRO for the past few days and know the pain 😶‍🌫️ of converting the leads.

**Comment by jonathimer** [comment]
**to-do**
add "[Don't have an account yet? Create an account](https://app.crowd.dev/auth/signup)" to the bottom of the sign-in form on app.crowd.dev/auth/signin

**Comment by yeganathan18** [comment]
Yup, I just opened a PR for the issue 🛠️

**Comment by yeganathan18** [comment]
Closing this issue, since the pr for the same is merged. Cheers! 🍻

**Comment by jonathimer** [comment]
Thanks agaon @yeganathan18 🙏
