### ISSUE TITLE
[C-1201] Add "# of activities" column to all views

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#779]
### crowd.dev edition

Cloud (hosted)

### Link

https://app.crowd.dev/members?activeTab=most-engaged

### Describe the problem

Currently, we only display "# of activities" column in the "Most engaged" view. This is confusing because its an important attribute and users can also filter by it in other views.

### Describe the improvement

Add "# of activities" column to all views.

### Additional context

n/a

<sub>[C-1201](https://linear.app/crowddotdev/issue/C-1201/add-of-activities-column-to-all-views)</sub>

**Comment by peoray** [comment]
hey @jonathimer :)
Can you provide a visual representation of this improvement? 
would love to work on a pr :)

**Comment by jonathimer** [comment]
cc @nunoeufrasio 

can you perhaps help here? :)

**Comment by nunoeufrasio** [comment]
Thanks in advance for working on this @peoray 

Here's a preview ⬇️
<img width="645" alt="# of activities" src="https://user-images.githubusercontent.com/22342669/233319346-4e368ebf-c5ea-4c1f-992a-7bee4fd06a29.png">

- this column can go right after "Organization & title" in all views;
- you can keep the 200px width as in "Most engaged" view and the sorting;

**Comment by peoray** [comment]
Thank you so much @nunoeufrasio. Just to be clear, when @jonathimer says all views, this is referring to the `/members` pages right? The views for:
- All members
- New and Active
- Slipping away
- Most engaged
- Team members

**Comment by jonathimer** [comment]
Yes, exactly!
