### ISSUE TITLE
[C-1225] Can't add webhooks

### ISSUE THREAD

**Issue by supersalty911** [CrowdDotDev/crowd.dev#791]
### crowd.dev edition

Cloud (hosted)

### What happened?

While writing an automation with Zapier, no webhooks have been added to automations page of crowd.dev like it did before. I tried manually creating one, but it failed to turn on

<sub>[C-1225](https://linear.app/crowddotdev/issue/C-1225/cant-add-webhooks)</sub>

**Comment by jonathimer** [comment]
@supersalty911 Thanks for letting us know! We are looking into this.

Did you receive any error message?

**Comment by supersalty911** [comment]
Hi Jonathan,

After trying to turn the zaps on, I received an email from Zapier that they
couldn't turn the zaps on. While trying to make my own webhook on the
crowd.dev site, I got a "whoops, something went wrong. Please try again"
etc pop up.

Thanks for looking into this.

**Comment by jonathimer** [comment]
Can you share your tenantID with me? You can find it [here](https://app.crowd.dev/settings?activeTab=api-keys)

**Comment by supersalty911** [comment]
Hi, here it is:
ca1122ba-1cda-49cc-ba0d-49d8bde0fb5e

**Comment by garrrikkotua** [comment]
Hi @supersalty911 ,

Everyhing should work as expected now. Thanks for reporting this!
