### ISSUE TITLE
[C-1258] Filter by custom 'Activity Type' is not working

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#802]
### crowd.dev edition

Cloud (hosted)

### Version

Frontend - 0.5.0

### What happened?

Filter by custom  'Activity Type' is not working. 
Even though such activities are present.

<img width="1179" alt="Screenshot 2023-04-24 at 5 35 34 PM" src="https://user-images.githubusercontent.com/87848481/233994485-a50d8bd8-c9fd-4ac1-b649-7332f8599319.png">

<img width="1110" alt="Screenshot 2023-04-24 at 5 54 14 PM" src="https://user-images.githubusercontent.com/87848481/233995398-7cb7d0d0-fe7d-4638-aec4-2ef1c303a1ed.png">

<sub>[C-1258](https://linear.app/crowddotdev/issue/C-1258/filter-by-custom-activity-type-is-not-working)</sub>

**Comment by keshari1arya** [comment]
@RaginiAngarka I have tried to reproduce but its working fine with the latest code in local. It seems fixed.
![image](https://user-images.githubusercontent.com/16665888/235311970-b2375b43-6146-4bfe-aff1-2bf8d328495a.png)

**Comment by RaginiAngarka** [comment]
@keshari1arya , checked on Cloud (hosted) version.  After selecting 'Activity Type' from filters, the drop down to select 'Activity Type' is not showing up in UI. 
The drop down was getting displayed previously but activities were not getting filtered, but now drop down is not showing up to select Custom Activity type. 
Not sure how to proceed further to test.

**Comment by keshari1arya** [comment]
@RaginiAngarka I have not found any difficulty selecting custom activity type and filtering against it.

<img width="1157" alt="Screenshot 2023-05-02 at 11 27 05 PM" src="https://user-images.githubusercontent.com/16665888/235747046-3ca27e67-ac1b-4e2b-83cb-83e4fedf64af.png">

if you are having same issue i suggest to hard refresh or clear cache and then start checking it. if it still persist please feel free to create a tiny screen recording of the steps so that it will be helpful to find out. 

![image](https://user-images.githubusercontent.com/16665888/235747926-cbc30d92-432b-45de-aca7-5d880a3970cd.png)


(may be you have a special case which will be interesting for us to tackle)

**Comment by RaginiAngarka** [comment]
@keshari1arya Please check the recording for your reference. I think the issue is, you are checking on app.crowd.dev and issue is on linux.crowd.dev

https://user-images.githubusercontent.com/87848481/235878935-d53d2499-7e6f-434f-b6c3-d9aec5d614c5.mov

**Comment by keshari1arya** [comment]
Hey @RaginiAngarka 
In linux.crowd.dev i am able to get the desired operation. I thing there might be some issue with your login if you have refreshed your browser. Please start a conversation in discord or anywhere else for quick check for in depth scan of the bug.

![Screenshot 2023-05-03 at 9 51 37 PM](https://user-images.githubusercontent.com/16665888/235978935-6caf0d8d-e0d5-492c-a489-9147bcd6d6b5.png)

**Comment by RaginiAngarka** [comment]
@keshari1arya , tried on different machine and for different user, still the drop down to select 'Activity Type' is not showing up in UI. The issue still exists.

**Comment by RaginiAngarka** [comment]
Hi @joanagmaia , I tried this, it still not working for linux.crowd.dev. Please check the recording attached. Thanks.

https://github.com/CrowdDotDev/crowd.dev/assets/87848481/555028f2-6c19-4792-8386-bc0b63db7f36

**Comment by joanagmaia** [comment]
Hey @RaginiAngarka, apologies for the issue once again. There was indeed another edge case from bad data that we had not foreseen. We already created an issue to tackle it but until it's fixed I've protected against it in the frontend, so if you don't mind I would ask you to re-check if the problem persists
