### ISSUE TITLE
[C-1283] Not able to Delete Custom Activity Type

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#813]
### crowd.dev edition

Cloud (hosted)

### Version

Frontend - 0.5.0

### What happened?

Not able to delete custom Activity.  When we click on 'Delete Activity' button nothing is happening on UI.

Checked the network tab, looks like API is getting  getting 400, please check the screen shot attached.
Looks like the issue is related to the name of Activity - there is special character in the name. In this case it is (`%`).
Is this an issue then the create activity API should not allow special characters like `%` in first place.

<img width="1439" alt="Screenshot 2023-04-27 at 10 12 47 AM" src="https://user-images.githubusercontent.com/87848481/234854681-e638fb08-5689-478a-93c5-949fbf5b72fd.png">

<sub>[C-1283](https://linear.app/crowddotdev/issue/C-1283/not-able-to-delete-custom-activity-type)</sub>

**Comment by epipav** [comment]
also related #863
