### ISSUE TITLE
[C-1334] Count of Forks are not matching with actual repository on Github

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#826]
### crowd.dev edition

Cloud (hosted)

### Version

Frontend - 0.5.0

### What happened?

Count of Forks in crowd.dev are not matching with count of forks on actual repository on GitHub
Checked the count in database as well it is not matching. 
Expected Result:-  Count of forks on crowd.dev and actual repository should match.

<img width="1433" alt="Screenshot 2023-05-03 at 2 20 52 PM" src="https://user-images.githubusercontent.com/87848481/235873082-7f3bf202-019a-437e-aa98-aacaea6ff3d1.png">

<img width="1440" alt="Screenshot 2023-05-03 at 2 25 00 PM" src="https://user-images.githubusercontent.com/87848481/235873140-4b7c2b2f-7853-4e58-9e7d-7f0d8d919797.png">

<img width="1159" alt="Screenshot 2023-05-03 at 2 24 39 PM" src="https://user-images.githubusercontent.com/87848481/235873287-8389cd81-1041-4fcb-918f-823d0968fcfd.png">

<sub>[C-1334](https://linear.app/crowddotdev/issue/C-1334/count-of-forks-are-not-matching-with-actual-repository-on-github)</sub>

**Comment by joanreyero** [comment]
Hey Ragini!

Thanks for opening the issue. Could you reconnect the integration and see if the problem persists when it's connected again? GitHub had an issue with their forks endpoint last week.

**Comment by mlehotskylf** [comment]
@joanreyero we reconnected GitHub connector/integration but issue persist (we still see only 40 forks instead of 46).

**Comment by RaginiAngarka** [comment]
@joanreyero , can you please link the issue here which you have raised with GitHub related to this? Thanks.

**Comment by joanreyero** [comment]
Moving this to the LF repo
