### ISSUE TITLE
[C-1304] Always show "team members excluded" filter in members & activities list

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#828]
**Problem**

*Currently we never show where we are filtering team members out, this is causing confusion with users*

**Solution**

1. let users choose filter for team members
2. always show which filters are actually turned on (/members and /activities)

![GitHub-hosted image](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/d302c4e2-8f60-464f-9bb7-5c4d88a68b40/467f4cb0-8e90-43e6-ac22-02f735d7d44d)

[Source image](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/d302c4e2-8f60-464f-9bb7-5c4d88a68b40/467f4cb0-8e90-43e6-ac22-02f735d7d44d)

* For all modules that have default filters, display them to the user and allow the user to edit them without deleting.

**UI Solution**

Have non deletable filters which would be applied already by default. Users wouldn't be able to delete filter but just apply changes based on what they want to see. With that we would make clear to users when default filters are applied

![GitHub-hosted image](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/4c4ea9a3-66a0-453b-8b24-32a080e7f900/1c725ca3-7ff1-4103-9799-3b3c75b319dc)

[Source image](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/4c4ea9a3-66a0-453b-8b24-32a080e7f900/1c725ca3-7ff1-4103-9799-3b3c75b319dc)

![](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/c662490d-02db-4328-a164-6b25d15b36cf/d8b5fe21-047b-4471-b942-b3a87053a739)

[Source image](https://github.com/CrowdDotDev/crowd.dev/assets/20134207/30ea00f9-5bf8-4ffa-8843-242989958159)

**Dev Specs**

* Currently the filters configuration is within `frontend/src/modules/{module}/config` folder. This folder contains all configuration for both the custom filters that can be applied by the user but also the default filters that are always applied.
* For the default filters, the configuration is within `frontend/src/modules/{module}/config/settings`, so for instance in the Members page there is a default filter for `isBot: false`. To apply this by default we have a configuration file for it in `frontend/src/modules/member/config/settings/bot.ts`. Same applies for all other default filters and modules.

To achieve the desired UI solution, you will need to update `modules/filters/components/Filter.vue` component which is currently responsible to list all of the applied filters. However, at the moment it is only rendering the filters returned from `alignFilterList`, which is excluding the filters from `settings`. Refactor this component so user can also see default filters.

You can use `MultiSelectFilter.vue` component to render the filter component, but will probably need to create a customization of how the filter label is rendered -> `Hide: Team Members, Bots`

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1304](https://linear.app/crowddotdev/issue/C-1304/always-show-team-members-excluded-filter-in-members-and-activities)</sub>

**Comment by keshari1arya** [comment]
Hey @jonathimer,
what i have understood from the description is 

- a filter attribute "Team Member : is false" is getting attached when we move to Team Member tab under members. But when we search for Team Member filter its not visible. So we need add Team Member filter attribute to filter. Is my understanding correct?
- And also what about activities as i can see there are no filter added by default to recent activities. and when we move to conversation tab the default filter is "Last Activity : is After XXXXX" . i am little confused.
Kindly guide me to understand the requirement.

**Comment by joanagmaia** [comment]
Hey @keshari1arya thanks again for your interest in contributing 😄 
Just to follow up on your questions:
- Your first assumption is correct. Even though we pass that filter to the request, we don't show it anywhere in the UI. We should add the filter to the Filters dropdown and to the page above the members list (if selected/applied - just like the image in the issue)
- In the activities page the issue is the same. Some filters are applied by default that are not visible to the user. The one you are seeing (Last activity) is ok, since we allow the user to see it and change it. Each tab has it's own filters applied.

I've added a more detailed description to the issue on how it could be tackled. I've referenced some files in the frontend that point to where we are adding these configurations.

Please let me know if the information I provided is enough for you to get started. If not feel free ask for any help you need along the way 🙏

**Comment by Dhruwang** [comment]
Is this issue resolved ?

**Comment by jonathimer** [comment]
Nop, this issue is still open!

That said, we are currently working on a full refactor of our filters and probably can tackle this as part of it.

cc @gaspergrom

**Comment by Dhruwang** [comment]
Ok. Do let me know if there is something for me.

**Comment by peoray** [comment]
@jonathimer @joanagmaia 
Is this still a valid issue? 
If yes, does the detailed description still apply given the refactoring?

**Comment by joanagmaia** [comment]
Hey @peoray,
Yes it's still a valid issue, thanks for your interest in picking it up! The filters approach has been refactored in the frontend so at the moment this should already be possible. I've just updated the description to give some high level explanation of what needs to be done

If you need any further help let me know!
@gaspergrom was the person responsible for the filters refactor. @gaspergrom feel free to add any more specs or suggested solutions to the issue description if you feel it's needed

**Comment by gaspergrom** [comment]
Hey, im already handling this issue with other project.
