### ISSUE TITLE
[C-1428] Create or update an activity is not working

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#854]
### crowd.dev edition

Cloud (hosted)

### Version

Frontend - 0.5.0

### What happened?

Was trying to call POST API to update/create an activity. (https://docs.crowd.dev/reference/post_tenant-tenantid-activity)
it is giving error as - `An unexpected error occurred`
Even though ‘memberId’ and platform passed is correct, it failing to create an activity. Can you please fix this. Thanks.

<img width="1043" alt="Screenshot 2023-05-12 at 1 01 21 PM" src="https://github.com/CrowdDotDev/crowd.dev/assets/87848481/8646b19f-22d7-40dc-a6fe-4843c7d276f1">

<sub>[C-1428](https://linear.app/crowddotdev/issue/C-1428/create-or-update-an-activity-is-not-working)</sub>

**Comment by epipav** [comment]
looks like an authorization issue - do you have the bearer auth token set?

**Comment by RaginiAngarka** [comment]
Thanks @anilb0stanci . Bearer token was mussing, but after that getting this error:-
`Cannot read properties of undefined (reading 'message')`

**Comment by joanreyero** [comment]
@RaginiAngarka, this `message` error was an error when logging another error. I just pushed a fix so we can see the proper message. Could you try again and share the new error message?

**Comment by RaginiAngarka** [comment]
@joanreyero , tried again.  Same error message.
<img width="1063" alt="Screenshot 2023-05-12 at 2 42 51 PM" src="https://github.com/CrowdDotDev/crowd.dev/assets/87848481/06912a7e-70ed-4948-bea0-dfca3dc5a679">

**Comment by nkukrejaind** [comment]
Hi @RaginiAngarka , are we facing still same error or this can be treated as resolved. 
Thanks
