### ISSUE TITLE
[C-1359] Activities Report: Activities by Platform bar doesn't take 100% width

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#865]
**problem:**

in the Activities Report, when selecting 7d/14d/30d/3m the horizontal bar shows like this:

![Bildschirmfoto 2023-05-15 um 20.55.18.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/22be8b7d-1b35-4d64-898a-644fd3cf90c0/93ed5397-88b2-4f10-9ee2-060082cec04a)

**expected behavior:**

the vertical bar should take 100% width (see below)

![Bildschirmfoto 2023-05-15 um 21.05.32.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/5f3e078d-398c-4ae6-b067-0c8f9c290fda/e61b268f-fb12-4d9f-8318-4e10c004cf64)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1359](https://linear.app/crowddotdev/issue/C-1359/activities-report-activities-by-platform-bar-doesnt-take-100percent)</sub>

**Comment by joanagmaia** [comment]
This issue should be fixed

![Screenshot 2023-08-17 at 18.57.47.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/a0464ecb-ed82-4cdc-9137-116c134db0ae/db4811f7-dee1-4e7d-bebf-0b6e7b855a94)
