### ISSUE TITLE
[C-1360] Merging members: Profile with more identities should be the primary one by default

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#866]
When merging members, the primary member should always be the profile with more identities.

*In this example case, clearly the right profile should be the primary one.*

![Bildschirmfoto 2023-05-15 um 21.11.12.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/69e493f4-7d20-4164-960e-a5c9d05d9b94/9e8da040-4e14-4434-bb6d-24094c9dd8a9)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1360](https://linear.app/crowddotdev/issue/C-1360/merging-members-profile-with-more-identities-should-be-the-primary-one)</sub>

**Comment by harshil202** [comment]
Hello, @jonathimer  I would like to work on it can you assign me this task?

**Comment by jonathimer** [comment]
Awesome! Let us know if you need any help.

**Comment by yeganathan18** [comment]
Hey, @harshil202! Do you need any more help from our side to tackle the issue? 😊
