### ISSUE TITLE
[C-1361] Organization profile: Name is not centered when missing other attributes

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#870]
when missing attributes like website or location, the profile looks like the following

![Bildschirmfoto 2023-05-16 um 07.11.08.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/fa76359f-cd6f-42ce-b695-252766aba4da/4bf99c6a-2f08-4ca2-a5bd-bb91b6e0eee0)

**expected**: the divison on the right should always be centered towards the logo

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1361](https://linear.app/crowddotdev/issue/C-1361/organization-profile-name-is-not-centered-when-missing-other)</sub>

**Comment by peoray** [comment]
@jonathimer can you give me more details here? Also, the image you linked does not work

**Comment by jonathimer** [comment]
Hey @peoray, I checked and this issue got already solved with #930
