### ISSUE TITLE
[C-1425] Count of stars not matching with actual repository on GitHub

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#874]
### crowd.dev edition

Cloud (hosted)

### Version

Frontend - 0.5.0

### What happened?

The count of star activities is not matching with actual GitHub repository.
Checked the count in database it is not matching.

Expected Result:- Count of stars on crowd.dev and actual repository should match.

select type, count(*) from activities where channel = 'https://github.com/communitybridge/easycla' and type like '%star' group by type;
---------------------
star 60
unstar 7

If we consider 'unstar' activities
i.e 
Total star activities = (count of star activities) - (count of unstar activities) 
Then Total star activities comes 53 i.e (60 -7) =  53
But the count of star activities is still less by 1 number as compared to actual GitHub repo.

Tried looking further into the issue, looks like there is one extra 'unstar' activity in the DB, hence the count of 'unstar' activities are more as compared to GitHub. Hence the total star activities count is coming less by 1 number.

<img width="956" alt="Screenshot 2023-05-16 at 5 41 11 PM" src="https://github.com/CrowdDotDev/crowd.dev/assets/87848481/e07de49a-51d3-474e-870a-29e093b93672">

If you check GitHub repo there is no user 'spacedog' in Stargazers.

Can you please fix this data issue. Thanks

<sub>[C-1425](https://linear.app/crowddotdev/issue/C-1425/count-of-stars-not-matching-with-actual-repository-on-github)</sub>

**Comment by joanreyero** [comment]
Cloing since its the same as https://github.com/CrowdDotDev/crowd.dev/issues/858
