### ISSUE TITLE
[C-1424] Activities by Bots are not getting captured

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#877]
### crowd.dev edition

Cloud (hosted)

### Version

Frontend - 0.5.0

### What happened?

Currently crowd.dev is not collecting data for PRs (rather all activities) created by bots.
We need this data in DB and have ability to filter out activities by bots. 

Can we capture all the bot activities?
May be we can add a field in the activity indicating it is a bot activity or not.

<sub>[C-1424](https://linear.app/crowddotdev/issue/C-1424/activities-by-bots-are-not-getting-captured)</sub>

**Comment by nkukrejaind** [comment]
Hi @joanreyero, we know this is of medium priority bug but can you please let us know tentatively by when we will have this feature available. Can we assume safely to be available by end of June or before Mid of July? Please confirm.
