### ISSUE TITLE
[C-1375] Member enrichment doesn't fill out job title

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#885]
**problem**

when enriching a member, it fetches the work experience but the "job title" and "company" dont get filled out

*example member*: [https://app.crowd.dev/members/3977fdd6-c6cb-49d4-a07d-a362e9f3f0ac](https://app.crowd.dev/members/3977fdd6-c6cb-49d4-a07d-a362e9f3f0ac)

**solution**

if we don't get the job titles as a separate attribute, we should fetch it from work experience

* Job title might come from enrichment, but it is not really being added as an attribute. It should be.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1375](https://linear.app/crowddotdev/issue/C-1375/member-enrichment-doesnt-fill-out-job-title)</sub>

**Comment by elayira** [comment]
@jonathimer I'd like to create a fix for this issue.

**Comment by jonathimer** [comment]
Awesome! assigned you to the issue

**Comment by jonathimer** [comment]
Please not that its referring to the member enrichment (not organization enrichment)
