### ISSUE TITLE
[C-1455] Display which Twitter account an activity is referring to

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#907]
### What problem are you trying to solve?

for Twitter activities we currently only display activity bodys like "followed you"
if a user connected several accounts (e.g. via Zapier) they should be able to differentiate which account the member followed

example from member profile:
<img width="692" alt="Bildschirmfoto 2023-05-26 um 14 06 54" src="https://github.com/CrowdDotDev/crowd.dev/assets/41432658/f9a524bf-07b5-4fc8-9066-01ad3dd9a58c">

### What's your suggested solution?

add the Twitter account to the body, e.g. "followed [jonathimer](https://twitter.com/jonathimer)" (similar to how we already do it for GitHub activites with repo reference)

<sub>[C-1455](https://linear.app/crowddotdev/issue/C-1455/display-which-twitter-account-activity-is-referring-to)</sub>

**Comment by ganeshmani** [comment]
@jonathimer I would like to work on this issue

**Comment by jonathimer** [comment]
Sure! I assigned the issue to you. If you need any help, [say hello on Discord](http://crowd.dev/discord).
