### ISSUE TITLE
[C-1470] Organization profile -> Activity Feed: Line break for new members

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#920]
**Problem**

On Organizations profile → Activities feed, the line breaks if the member has the "new" tag

![Bildschirmfoto 2023-05-30 um 16.46.16.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/aab63f94-8326-4b41-b05d-85911d1e50b6/66a7eaaa-0f0f-4742-9102-bf7a8a95c8b2)

**Solution**

The tag should appear next to the name, not in a new line

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1470](https://linear.app/crowddotdev/issue/C-1470/organization-profile-activity-feed-line-break-for-new-members)</sub>

**Comment by yashsharma999** [comment]
Hey! can you assign this issue to me ?

**Comment by joanreyero** [comment]
Hey! Glad to have you here! Sure 😊 we will keep this for you. Just open a PR when you are ready! Let us know if you need any help.
