### ISSUE TITLE
[C-1502] Exclude bots from automations

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#941]
similar to team members, we should exclude bots from automations by default

we could add a toggle to turn this on/off as well

**current state (example)**

Member (which is a bot):

<img width="1724" alt="Bildschirmfoto 2023-06-02 um 14 33 00" src="https://github.com/CrowdDotDev/crowd.dev/assets/63534555/a4553990-de0b-4596-afa8-3d53c5c633ec">

Slack notification (triggered for this):

<img width="644" alt="Bildschirmfoto 2023-06-02 um 14 32 55" src="https://github.com/CrowdDotDev/crowd.dev/assets/63534555/ee330379-acde-43ec-bdf5-62f4ed135638">

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1502](https://linear.app/crowddotdev/issue/C-1502/exclude-bots-from-automations)</sub>

**Comment by amisdun** [comment]
@jonathimer is this issue supposed to prevent bots from triggering an events by default? Also where can I find implementation for bots from the codebase.

**Comment by garrrikkotua** [comment]
Hi @amisdun 

It's quite complicated to trigger the automation with the code, I guess we would need to prepare a script for it.

In the meantime, I think the easiest option to test it would be through the app:

1. Go to settings -> automations and create a new webhook automation
2. For webhooks use something like webhook.site
3. Finally, do some action in the app to trigger your automation (e.g connect some integration)

Yeah I know it's quite complicated, sorry about that. We will try to prepare some script.
