### ISSUE TITLE
[C-1521] Signin page opens even after authentication

### ISSUE THREAD

**Issue by Dhruwang** [CrowdDotDev/crowd.dev#958]
### crowd.dev edition

Cloud (hosted)

## Steps to reproduce

1. First Sign-in/signup
2. Now when you are on the home page, try to go back
3. It will open sign-in page again.

Ideally it should not allow user to open sign-in page after authentication 

https://github.com/CrowdDotDev/crowd.dev/assets/67850763/f66ea925-7fa2-4f2e-bee1-5dca28e3ef9f

<sub>[C-1521](https://linear.app/crowddotdev/issue/C-1521/signin-page-opens-even-after-authentication)</sub>

**Comment by Charlotte0709** [comment]
Thanks for sharing! We are checking on this.
