### ISSUE TITLE
[C-1523] Improve UX copy of negative filters

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#963]
**Problem**

A user mentioned in an interview that he would love to use negative filters. We already have this functionality, but its quite hidden:

![Bildschirmfoto 2023-06-07 um 15.17.12.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/f5dcf7de-f04d-497f-ac67-61aadd35ed54/0f5290fe-80e1-41c7-b669-6d3f0f08458e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FlYmVjN2FkLTU2NDktNDc1OC05YmVkLTA2MWY3MjI4YTg3OS9mNWRjZjdkZS1mMDRkLTQ5N2YtYWM2Ny02MWFhZGQzNWVkNTQvMGY1MjkwZmUtODBlMS00MWM3LWI2NjktNmQzZjBmMDg0NThlIiwiaWF0IjoxNjkzNTY3NjkyLCJleHAiOjE2OTM2NTQwOTJ9.9r9h63Sca3YVj-U1WDMSQKgSkVUwUSflfKcNKeuo-Ac)

**Solution**

Add a tooltip that says "If excluded, turns the filter into a negative condition"

![image.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/28774377-5083-4b7d-9c63-f579dc1bf5a3/9f65e7cc-c931-48ff-b0b0-08b14fb69582?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2FlYmVjN2FkLTU2NDktNDc1OC05YmVkLTA2MWY3MjI4YTg3OS8yODc3NDM3Ny01MDgzLTRiN2QtOWM2My1mNTc5ZGMxYmY1YTMvOWY2NWU3Y2MtYzkzMS00OGZmLWIwYjAtMDhiMTRmYjY5NTgyIiwiaWF0IjoxNjkzNTY3NjkyLCJleHAiOjE2OTM2NTQwOTJ9.zyUUIbT4ms0eNroNoGiwQWoZl9OUMRw35LYtT_LY2BQ)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1523](https://linear.app/crowddotdev/issue/C-1523/improve-ux-copy-of-negative-filters)</sub>

**Comment by Dhruwang** [comment]
@jonathimer  So this tooltip should be displayed when a user hovers over it ?

**Comment by jonathimer** [comment]
@nunoeufrasio - could you help out with design specs? :)

**Comment by roy9495** [comment]
hi, the image is not visible

**Comment by nunoeufrasio** [comment]
Hi @roy9495 @Dhruwang 
Latest design version, the tooltip becomes visible when hovering over the question mark icon.
<img width="1287" alt="Negative filters" src="https://github.com/CrowdDotDev/crowd.dev/assets/22342669/88876693-6efd-4afa-a048-dda0db982313">

**Comment by peoray** [comment]
can I pick this up?

**Comment by joanagmaia** [comment]
@peoray of course 😄 
The latest design is in this comment https://github.com/CrowdDotDev/crowd.dev/issues/963#issuecomment-1640059444
