### ISSUE TITLE
[C-1562] Cant add organization

### ISSUE THREAD

**Issue by Dhruwang** [CrowdDotDev/crowd.dev#972]
### crowd.dev edition

Cloud (hosted)

### What happened?

# Steps to reproduce

1. Go to organizations page
2. Click on Add Organization
3. Fill out required fields (name)
4. click  add organization

It shows can alert saying organization created but actually it do not get listed on organizations page

[Screencast from 10-06-23 01:52:50 PM IST.webm](https://github.com/CrowdDotDev/crowd.dev/assets/67850763/86404466-ada0-48a4-b152-e3c16d97e6f4)

<sub>[C-1562](https://linear.app/crowddotdev/issue/C-1562/cant-add-organization)</sub>

**Comment by Dhruwang** [comment]
Would like to work on this !

**Comment by Charlotte0709** [comment]
Hey @Dhruwang, thanks for finding this. Yes, would be great if you could work on it.

**Comment by Dhruwang** [comment]
In `backend/src/database/repositories/organizationRepository.ts
`
On line 472,
![Screenshot from 2023-06-12 18-01-28](https://github.com/CrowdDotDev/crowd.dev/assets/67850763/2d90076c-5761-4c2a-a7d8-72fdd01ed97b)

Here we are setting `includeOrganizationsWithoutMembers` as false so organization with 0 members will not be shown
But when a user creates a new organization, members will be 0 by default and hence organization get created in db but are not shown 

So is there a specific reason why that is set to false ?

**Comment by joanreyero** [comment]
Hi! I think there was a reason: some members first had an organisation, and then the association was removed by an integration. However, I think this might have been due to a bug that was already fixed. I think we can remove this and return all organizations.

**Comment by Dhruwang** [comment]
Ok then , I would make the required changes
