### ISSUE TITLE
[C-1644] Default reports: add a widget that shows cumulative count of engaged members

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#993]
From a user:
At the moment I have this graph, which shows me the cumulative count of members with an engagement score of 4 or higher, but separated by score.
What I would like is just one line that's the sum of all members with a score of 4 or higher

I think this is a good metric to track.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1644](https://linear.app/crowddotdev/issue/C-1644/default-reports-add-a-widget-that-shows-cumulative-count-of-engaged)</sub>

**Comment by Dhruwang** [comment]
Can i get some more insights on this ?
Exactly what is to be done?

**Comment by lianmakesthings** [comment]
Hi @Dhruwang, I'm the user who asked for this feature originally.
Could you clarify what information exactly you are missing?
